// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/inventory/pos_consume/pos_consume.proto

package posconsumepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	POSConsumeService_ConsumeDirectProduct_FullMethodName  = "/inventory.pos_consume.POSConsumeService/ConsumeDirectProduct"
	POSConsumeService_ReverseConsumeProduct_FullMethodName = "/inventory.pos_consume.POSConsumeService/ReverseConsumeProduct"
)

// POSConsumeServiceClient is the client API for POSConsumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type POSConsumeServiceClient interface {
	ConsumeDirectProduct(ctx context.Context, in *ConsumeDirectProductRequest, opts ...grpc.CallOption) (*ConsumeDirectProductResponse, error)
	ReverseConsumeProduct(ctx context.Context, in *ReverseConsumeProductRequest, opts ...grpc.CallOption) (*ReverseConsumeProductResponse, error)
}

type pOSConsumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPOSConsumeServiceClient(cc grpc.ClientConnInterface) POSConsumeServiceClient {
	return &pOSConsumeServiceClient{cc}
}

func (c *pOSConsumeServiceClient) ConsumeDirectProduct(ctx context.Context, in *ConsumeDirectProductRequest, opts ...grpc.CallOption) (*ConsumeDirectProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeDirectProductResponse)
	err := c.cc.Invoke(ctx, POSConsumeService_ConsumeDirectProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pOSConsumeServiceClient) ReverseConsumeProduct(ctx context.Context, in *ReverseConsumeProductRequest, opts ...grpc.CallOption) (*ReverseConsumeProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseConsumeProductResponse)
	err := c.cc.Invoke(ctx, POSConsumeService_ReverseConsumeProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// POSConsumeServiceServer is the server API for POSConsumeService service.
// All implementations must embed UnimplementedPOSConsumeServiceServer
// for forward compatibility.
type POSConsumeServiceServer interface {
	ConsumeDirectProduct(context.Context, *ConsumeDirectProductRequest) (*ConsumeDirectProductResponse, error)
	ReverseConsumeProduct(context.Context, *ReverseConsumeProductRequest) (*ReverseConsumeProductResponse, error)
	mustEmbedUnimplementedPOSConsumeServiceServer()
}

// UnimplementedPOSConsumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPOSConsumeServiceServer struct{}

func (UnimplementedPOSConsumeServiceServer) ConsumeDirectProduct(context.Context, *ConsumeDirectProductRequest) (*ConsumeDirectProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeDirectProduct not implemented")
}
func (UnimplementedPOSConsumeServiceServer) ReverseConsumeProduct(context.Context, *ReverseConsumeProductRequest) (*ReverseConsumeProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseConsumeProduct not implemented")
}
func (UnimplementedPOSConsumeServiceServer) mustEmbedUnimplementedPOSConsumeServiceServer() {}
func (UnimplementedPOSConsumeServiceServer) testEmbeddedByValue()                           {}

// UnsafePOSConsumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to POSConsumeServiceServer will
// result in compilation errors.
type UnsafePOSConsumeServiceServer interface {
	mustEmbedUnimplementedPOSConsumeServiceServer()
}

func RegisterPOSConsumeServiceServer(s grpc.ServiceRegistrar, srv POSConsumeServiceServer) {
	// If the following call panics, it indicates UnimplementedPOSConsumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&POSConsumeService_ServiceDesc, srv)
}

func _POSConsumeService_ConsumeDirectProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeDirectProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSConsumeServiceServer).ConsumeDirectProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSConsumeService_ConsumeDirectProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSConsumeServiceServer).ConsumeDirectProduct(ctx, req.(*ConsumeDirectProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _POSConsumeService_ReverseConsumeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseConsumeProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSConsumeServiceServer).ReverseConsumeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSConsumeService_ReverseConsumeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSConsumeServiceServer).ReverseConsumeProduct(ctx, req.(*ReverseConsumeProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// POSConsumeService_ServiceDesc is the grpc.ServiceDesc for POSConsumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var POSConsumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.pos_consume.POSConsumeService",
	HandlerType: (*POSConsumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumeDirectProduct",
			Handler:    _POSConsumeService_ConsumeDirectProduct_Handler,
		},
		{
			MethodName: "ReverseConsumeProduct",
			Handler:    _POSConsumeService_ReverseConsumeProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory/pos_consume/pos_consume.proto",
}
