// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/pos_consume/pos_consume.proto

package posconsumepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumeDirectProductLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeDirectProductLine) Reset() {
	*x = ConsumeDirectProductLine{}
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeDirectProductLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeDirectProductLine) ProtoMessage() {}

func (x *ConsumeDirectProductLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeDirectProductLine.ProtoReflect.Descriptor instead.
func (*ConsumeDirectProductLine) Descriptor() ([]byte, []int) {
	return file_proto_inventory_pos_consume_pos_consume_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeDirectProductLine) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ConsumeDirectProductLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ConsumeDirectProductRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	WarehouseId   uint64                      `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	UserId        uint64                      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReferenceId   uint64                      `protobuf:"varint,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                      `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	Lines         []*ConsumeDirectProductLine `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeDirectProductRequest) Reset() {
	*x = ConsumeDirectProductRequest{}
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeDirectProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeDirectProductRequest) ProtoMessage() {}

func (x *ConsumeDirectProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeDirectProductRequest.ProtoReflect.Descriptor instead.
func (*ConsumeDirectProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_pos_consume_pos_consume_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeDirectProductRequest) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *ConsumeDirectProductRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsumeDirectProductRequest) GetReferenceId() uint64 {
	if x != nil {
		return x.ReferenceId
	}
	return 0
}

func (x *ConsumeDirectProductRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *ConsumeDirectProductRequest) GetLines() []*ConsumeDirectProductLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ConsumeDirectProductResultLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitCost      float64                `protobuf:"fixed64,3,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	SubtotalCost  float64                `protobuf:"fixed64,4,opt,name=subtotal_cost,json=subtotalCost,proto3" json:"subtotal_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeDirectProductResultLine) Reset() {
	*x = ConsumeDirectProductResultLine{}
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeDirectProductResultLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeDirectProductResultLine) ProtoMessage() {}

func (x *ConsumeDirectProductResultLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeDirectProductResultLine.ProtoReflect.Descriptor instead.
func (*ConsumeDirectProductResultLine) Descriptor() ([]byte, []int) {
	return file_proto_inventory_pos_consume_pos_consume_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeDirectProductResultLine) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ConsumeDirectProductResultLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ConsumeDirectProductResultLine) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *ConsumeDirectProductResultLine) GetSubtotalCost() float64 {
	if x != nil {
		return x.SubtotalCost
	}
	return 0
}

type ConsumeDirectProductResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Success       bool                              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalCost     float64                           `protobuf:"fixed64,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Lines         []*ConsumeDirectProductResultLine `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeDirectProductResponse) Reset() {
	*x = ConsumeDirectProductResponse{}
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeDirectProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeDirectProductResponse) ProtoMessage() {}

func (x *ConsumeDirectProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_pos_consume_pos_consume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeDirectProductResponse.ProtoReflect.Descriptor instead.
func (*ConsumeDirectProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_pos_consume_pos_consume_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeDirectProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeDirectProductResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ConsumeDirectProductResponse) GetLines() []*ConsumeDirectProductResultLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_proto_inventory_pos_consume_pos_consume_proto protoreflect.FileDescriptor

const file_proto_inventory_pos_consume_pos_consume_proto_rawDesc = "" +
	"\n" +
	"-proto/inventory/pos_consume/pos_consume.proto\x12\x15inventory.pos_consume\"U\n" +
	"\x18ConsumeDirectProductLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\xea\x01\n" +
	"\x1bConsumeDirectProductRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x04R\vwarehouseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\freference_id\x18\x03 \x01(\x04R\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\x12E\n" +
	"\x05lines\x18\x05 \x03(\v2/.inventory.pos_consume.ConsumeDirectProductLineR\x05lines\"\x9d\x01\n" +
	"\x1eConsumeDirectProductResultLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x1b\n" +
	"\tunit_cost\x18\x03 \x01(\x01R\bunitCost\x12#\n" +
	"\rsubtotal_cost\x18\x04 \x01(\x01R\fsubtotalCost\"\xa4\x01\n" +
	"\x1cConsumeDirectProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x01R\ttotalCost\x12K\n" +
	"\x05lines\x18\x03 \x03(\v25.inventory.pos_consume.ConsumeDirectProductResultLineR\x05lines2\x94\x01\n" +
	"\x11POSConsumeService\x12\x7f\n" +
	"\x14ConsumeDirectProduct\x122.inventory.pos_consume.ConsumeDirectProductRequest\x1a3.inventory.pos_consume.ConsumeDirectProductResponseBIZGgithub.com/InBitGT/proto-definitions/inventory/pos_consume;posconsumepbb\x06proto3"

var (
	file_proto_inventory_pos_consume_pos_consume_proto_rawDescOnce sync.Once
	file_proto_inventory_pos_consume_pos_consume_proto_rawDescData []byte
)

func file_proto_inventory_pos_consume_pos_consume_proto_rawDescGZIP() []byte {
	file_proto_inventory_pos_consume_pos_consume_proto_rawDescOnce.Do(func() {
		file_proto_inventory_pos_consume_pos_consume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_pos_consume_pos_consume_proto_rawDesc), len(file_proto_inventory_pos_consume_pos_consume_proto_rawDesc)))
	})
	return file_proto_inventory_pos_consume_pos_consume_proto_rawDescData
}

var file_proto_inventory_pos_consume_pos_consume_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_inventory_pos_consume_pos_consume_proto_goTypes = []any{
	(*ConsumeDirectProductLine)(nil),       // 0: inventory.pos_consume.ConsumeDirectProductLine
	(*ConsumeDirectProductRequest)(nil),    // 1: inventory.pos_consume.ConsumeDirectProductRequest
	(*ConsumeDirectProductResultLine)(nil), // 2: inventory.pos_consume.ConsumeDirectProductResultLine
	(*ConsumeDirectProductResponse)(nil),   // 3: inventory.pos_consume.ConsumeDirectProductResponse
}
var file_proto_inventory_pos_consume_pos_consume_proto_depIdxs = []int32{
	0, // 0: inventory.pos_consume.ConsumeDirectProductRequest.lines:type_name -> inventory.pos_consume.ConsumeDirectProductLine
	2, // 1: inventory.pos_consume.ConsumeDirectProductResponse.lines:type_name -> inventory.pos_consume.ConsumeDirectProductResultLine
	1, // 2: inventory.pos_consume.POSConsumeService.ConsumeDirectProduct:input_type -> inventory.pos_consume.ConsumeDirectProductRequest
	3, // 3: inventory.pos_consume.POSConsumeService.ConsumeDirectProduct:output_type -> inventory.pos_consume.ConsumeDirectProductResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_inventory_pos_consume_pos_consume_proto_init() }
func file_proto_inventory_pos_consume_pos_consume_proto_init() {
	if File_proto_inventory_pos_consume_pos_consume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_pos_consume_pos_consume_proto_rawDesc), len(file_proto_inventory_pos_consume_pos_consume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_pos_consume_pos_consume_proto_goTypes,
		DependencyIndexes: file_proto_inventory_pos_consume_pos_consume_proto_depIdxs,
		MessageInfos:      file_proto_inventory_pos_consume_pos_consume_proto_msgTypes,
	}.Build()
	File_proto_inventory_pos_consume_pos_consume_proto = out.File
	file_proto_inventory_pos_consume_pos_consume_proto_goTypes = nil
	file_proto_inventory_pos_consume_pos_consume_proto_depIdxs = nil
}
