syntax = "proto3";

package inventory.warehouse;

option go_package = "github.com/InBitGT/proto-definitions/inventory/warehouse;warehousepb";

service WarehouseService {
  rpc GetDefaultWarehouseByBranch (GetDefaultWarehouseByBranchRequest) returns (GetDefaultWarehouseByBranchResponse);
  rpc ListWarehousesByBranches (ListWarehousesByBranchesRequest) returns (ListWarehousesByBranchesResponse);
}

message GetDefaultWarehouseByBranchRequest {
  uint64 branch_id = 1;
}

message GetDefaultWarehouseByBranchResponse {
  bool success = 1;
  uint64 warehouse_id = 2;
  string warehouse_name = 3;
}

message WarehouseItem {
  uint64 warehouse_id   = 1;
  string warehouse_name = 2;
}

message BranchWarehouses {
  uint64 branch_id                  = 1;
  repeated WarehouseItem warehouses = 2;
}

message ListWarehousesByBranchesRequest {
  repeated uint64 branch_ids = 1;
}

message ListWarehousesByBranchesResponse {
  bool success = 1;
  repeated BranchWarehouses branches = 2;
}