// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/warehouse/warehouse.proto

package warehousepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDefaultWarehouseByBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      uint64                 `protobuf:"varint,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultWarehouseByBranchRequest) Reset() {
	*x = GetDefaultWarehouseByBranchRequest{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultWarehouseByBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultWarehouseByBranchRequest) ProtoMessage() {}

func (x *GetDefaultWarehouseByBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultWarehouseByBranchRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultWarehouseByBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *GetDefaultWarehouseByBranchRequest) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

type GetDefaultWarehouseByBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WarehouseId   uint64                 `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	WarehouseName string                 `protobuf:"bytes,3,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultWarehouseByBranchResponse) Reset() {
	*x = GetDefaultWarehouseByBranchResponse{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultWarehouseByBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultWarehouseByBranchResponse) ProtoMessage() {}

func (x *GetDefaultWarehouseByBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultWarehouseByBranchResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultWarehouseByBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *GetDefaultWarehouseByBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDefaultWarehouseByBranchResponse) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *GetDefaultWarehouseByBranchResponse) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

type WarehouseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   uint64                 `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	WarehouseName string                 `protobuf:"bytes,2,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseItem) Reset() {
	*x = WarehouseItem{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseItem) ProtoMessage() {}

func (x *WarehouseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseItem.ProtoReflect.Descriptor instead.
func (*WarehouseItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *WarehouseItem) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *WarehouseItem) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

type BranchWarehouses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      uint64                 `protobuf:"varint,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Warehouses    []*WarehouseItem       `protobuf:"bytes,2,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchWarehouses) Reset() {
	*x = BranchWarehouses{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchWarehouses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchWarehouses) ProtoMessage() {}

func (x *BranchWarehouses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchWarehouses.ProtoReflect.Descriptor instead.
func (*BranchWarehouses) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *BranchWarehouses) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *BranchWarehouses) GetWarehouses() []*WarehouseItem {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type ListWarehousesByBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchIds     []uint64               `protobuf:"varint,1,rep,packed,name=branch_ids,json=branchIds,proto3" json:"branch_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesByBranchesRequest) Reset() {
	*x = ListWarehousesByBranchesRequest{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesByBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesByBranchesRequest) ProtoMessage() {}

func (x *ListWarehousesByBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesByBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesByBranchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *ListWarehousesByBranchesRequest) GetBranchIds() []uint64 {
	if x != nil {
		return x.BranchIds
	}
	return nil
}

type ListWarehousesByBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Branches      []*BranchWarehouses    `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesByBranchesResponse) Reset() {
	*x = ListWarehousesByBranchesResponse{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesByBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesByBranchesResponse) ProtoMessage() {}

func (x *ListWarehousesByBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesByBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListWarehousesByBranchesResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *ListWarehousesByBranchesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListWarehousesByBranchesResponse) GetBranches() []*BranchWarehouses {
	if x != nil {
		return x.Branches
	}
	return nil
}

type WarehouseWithBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   uint64                 `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	WarehouseName string                 `protobuf:"bytes,2,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	BranchId      uint64                 `protobuf:"varint,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseWithBranch) Reset() {
	*x = WarehouseWithBranch{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseWithBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseWithBranch) ProtoMessage() {}

func (x *WarehouseWithBranch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseWithBranch.ProtoReflect.Descriptor instead.
func (*WarehouseWithBranch) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *WarehouseWithBranch) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *WarehouseWithBranch) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

func (x *WarehouseWithBranch) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

type GetWarehousesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseIds  []uint64               `protobuf:"varint,1,rep,packed,name=warehouse_ids,json=warehouseIds,proto3" json:"warehouse_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesByIDsRequest) Reset() {
	*x = GetWarehousesByIDsRequest{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesByIDsRequest) ProtoMessage() {}

func (x *GetWarehousesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetWarehousesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *GetWarehousesByIDsRequest) GetWarehouseIds() []uint64 {
	if x != nil {
		return x.WarehouseIds
	}
	return nil
}

type GetWarehousesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Warehouses    []*WarehouseWithBranch `protobuf:"bytes,2,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesByIDsResponse) Reset() {
	*x = GetWarehousesByIDsResponse{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesByIDsResponse) ProtoMessage() {}

func (x *GetWarehousesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetWarehousesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *GetWarehousesByIDsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWarehousesByIDsResponse) GetWarehouses() []*WarehouseWithBranch {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

var File_proto_inventory_warehouse_warehouse_proto protoreflect.FileDescriptor

const file_proto_inventory_warehouse_warehouse_proto_rawDesc = "" +
	"\n" +
	")proto/inventory/warehouse/warehouse.proto\x12\x13inventory.warehouse\"A\n" +
	"\"GetDefaultWarehouseByBranchRequest\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\x04R\bbranchId\"\x89\x01\n" +
	"#GetDefaultWarehouseByBranchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x04R\vwarehouseId\x12%\n" +
	"\x0ewarehouse_name\x18\x03 \x01(\tR\rwarehouseName\"Y\n" +
	"\rWarehouseItem\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x04R\vwarehouseId\x12%\n" +
	"\x0ewarehouse_name\x18\x02 \x01(\tR\rwarehouseName\"s\n" +
	"\x10BranchWarehouses\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\x04R\bbranchId\x12B\n" +
	"\n" +
	"warehouses\x18\x02 \x03(\v2\".inventory.warehouse.WarehouseItemR\n" +
	"warehouses\"@\n" +
	"\x1fListWarehousesByBranchesRequest\x12\x1d\n" +
	"\n" +
	"branch_ids\x18\x01 \x03(\x04R\tbranchIds\"\x7f\n" +
	" ListWarehousesByBranchesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12A\n" +
	"\bbranches\x18\x02 \x03(\v2%.inventory.warehouse.BranchWarehousesR\bbranches\"|\n" +
	"\x13WarehouseWithBranch\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x04R\vwarehouseId\x12%\n" +
	"\x0ewarehouse_name\x18\x02 \x01(\tR\rwarehouseName\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\x04R\bbranchId\"@\n" +
	"\x19GetWarehousesByIDsRequest\x12#\n" +
	"\rwarehouse_ids\x18\x01 \x03(\x04R\fwarehouseIds\"\x80\x01\n" +
	"\x1aGetWarehousesByIDsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12H\n" +
	"\n" +
	"warehouses\x18\x02 \x03(\v2(.inventory.warehouse.WarehouseWithBranchR\n" +
	"warehouses2\xa6\x03\n" +
	"\x10WarehouseService\x12\x90\x01\n" +
	"\x1bGetDefaultWarehouseByBranch\x127.inventory.warehouse.GetDefaultWarehouseByBranchRequest\x1a8.inventory.warehouse.GetDefaultWarehouseByBranchResponse\x12\x87\x01\n" +
	"\x18ListWarehousesByBranches\x124.inventory.warehouse.ListWarehousesByBranchesRequest\x1a5.inventory.warehouse.ListWarehousesByBranchesResponse\x12u\n" +
	"\x12GetWarehousesByIDs\x12..inventory.warehouse.GetWarehousesByIDsRequest\x1a/.inventory.warehouse.GetWarehousesByIDsResponseBFZDgithub.com/InBitGT/proto-definitions/inventory/warehouse;warehousepbb\x06proto3"

var (
	file_proto_inventory_warehouse_warehouse_proto_rawDescOnce sync.Once
	file_proto_inventory_warehouse_warehouse_proto_rawDescData []byte
)

func file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP() []byte {
	file_proto_inventory_warehouse_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_inventory_warehouse_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_warehouse_warehouse_proto_rawDesc), len(file_proto_inventory_warehouse_warehouse_proto_rawDesc)))
	})
	return file_proto_inventory_warehouse_warehouse_proto_rawDescData
}

var file_proto_inventory_warehouse_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_inventory_warehouse_warehouse_proto_goTypes = []any{
	(*GetDefaultWarehouseByBranchRequest)(nil),  // 0: inventory.warehouse.GetDefaultWarehouseByBranchRequest
	(*GetDefaultWarehouseByBranchResponse)(nil), // 1: inventory.warehouse.GetDefaultWarehouseByBranchResponse
	(*WarehouseItem)(nil),                       // 2: inventory.warehouse.WarehouseItem
	(*BranchWarehouses)(nil),                    // 3: inventory.warehouse.BranchWarehouses
	(*ListWarehousesByBranchesRequest)(nil),     // 4: inventory.warehouse.ListWarehousesByBranchesRequest
	(*ListWarehousesByBranchesResponse)(nil),    // 5: inventory.warehouse.ListWarehousesByBranchesResponse
	(*WarehouseWithBranch)(nil),                 // 6: inventory.warehouse.WarehouseWithBranch
	(*GetWarehousesByIDsRequest)(nil),           // 7: inventory.warehouse.GetWarehousesByIDsRequest
	(*GetWarehousesByIDsResponse)(nil),          // 8: inventory.warehouse.GetWarehousesByIDsResponse
}
var file_proto_inventory_warehouse_warehouse_proto_depIdxs = []int32{
	2, // 0: inventory.warehouse.BranchWarehouses.warehouses:type_name -> inventory.warehouse.WarehouseItem
	3, // 1: inventory.warehouse.ListWarehousesByBranchesResponse.branches:type_name -> inventory.warehouse.BranchWarehouses
	6, // 2: inventory.warehouse.GetWarehousesByIDsResponse.warehouses:type_name -> inventory.warehouse.WarehouseWithBranch
	0, // 3: inventory.warehouse.WarehouseService.GetDefaultWarehouseByBranch:input_type -> inventory.warehouse.GetDefaultWarehouseByBranchRequest
	4, // 4: inventory.warehouse.WarehouseService.ListWarehousesByBranches:input_type -> inventory.warehouse.ListWarehousesByBranchesRequest
	7, // 5: inventory.warehouse.WarehouseService.GetWarehousesByIDs:input_type -> inventory.warehouse.GetWarehousesByIDsRequest
	1, // 6: inventory.warehouse.WarehouseService.GetDefaultWarehouseByBranch:output_type -> inventory.warehouse.GetDefaultWarehouseByBranchResponse
	5, // 7: inventory.warehouse.WarehouseService.ListWarehousesByBranches:output_type -> inventory.warehouse.ListWarehousesByBranchesResponse
	8, // 8: inventory.warehouse.WarehouseService.GetWarehousesByIDs:output_type -> inventory.warehouse.GetWarehousesByIDsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_warehouse_warehouse_proto_init() }
func file_proto_inventory_warehouse_warehouse_proto_init() {
	if File_proto_inventory_warehouse_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_warehouse_warehouse_proto_rawDesc), len(file_proto_inventory_warehouse_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_warehouse_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_inventory_warehouse_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_inventory_warehouse_warehouse_proto_msgTypes,
	}.Build()
	File_proto_inventory_warehouse_warehouse_proto = out.File
	file_proto_inventory_warehouse_warehouse_proto_goTypes = nil
	file_proto_inventory_warehouse_warehouse_proto_depIdxs = nil
}
