// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/warehouse/warehouse.proto

package warehousepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDefaultWarehouseByBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      uint64                 `protobuf:"varint,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultWarehouseByBranchRequest) Reset() {
	*x = GetDefaultWarehouseByBranchRequest{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultWarehouseByBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultWarehouseByBranchRequest) ProtoMessage() {}

func (x *GetDefaultWarehouseByBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultWarehouseByBranchRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultWarehouseByBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *GetDefaultWarehouseByBranchRequest) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

type GetDefaultWarehouseByBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WarehouseId   uint64                 `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	WarehouseName string                 `protobuf:"bytes,3,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultWarehouseByBranchResponse) Reset() {
	*x = GetDefaultWarehouseByBranchResponse{}
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultWarehouseByBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultWarehouseByBranchResponse) ProtoMessage() {}

func (x *GetDefaultWarehouseByBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_warehouse_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultWarehouseByBranchResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultWarehouseByBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *GetDefaultWarehouseByBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDefaultWarehouseByBranchResponse) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *GetDefaultWarehouseByBranchResponse) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

var File_proto_inventory_warehouse_warehouse_proto protoreflect.FileDescriptor

const file_proto_inventory_warehouse_warehouse_proto_rawDesc = "" +
	"\n" +
	")proto/inventory/warehouse/warehouse.proto\x12\x13inventory.warehouse\"A\n" +
	"\"GetDefaultWarehouseByBranchRequest\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\x04R\bbranchId\"\x89\x01\n" +
	"#GetDefaultWarehouseByBranchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x04R\vwarehouseId\x12%\n" +
	"\x0ewarehouse_name\x18\x03 \x01(\tR\rwarehouseName2\xa5\x01\n" +
	"\x10WarehouseService\x12\x90\x01\n" +
	"\x1bGetDefaultWarehouseByBranch\x127.inventory.warehouse.GetDefaultWarehouseByBranchRequest\x1a8.inventory.warehouse.GetDefaultWarehouseByBranchResponseBFZDgithub.com/InBitGT/proto-definitions/inventory/warehouse;warehousepbb\x06proto3"

var (
	file_proto_inventory_warehouse_warehouse_proto_rawDescOnce sync.Once
	file_proto_inventory_warehouse_warehouse_proto_rawDescData []byte
)

func file_proto_inventory_warehouse_warehouse_proto_rawDescGZIP() []byte {
	file_proto_inventory_warehouse_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_inventory_warehouse_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_warehouse_warehouse_proto_rawDesc), len(file_proto_inventory_warehouse_warehouse_proto_rawDesc)))
	})
	return file_proto_inventory_warehouse_warehouse_proto_rawDescData
}

var file_proto_inventory_warehouse_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inventory_warehouse_warehouse_proto_goTypes = []any{
	(*GetDefaultWarehouseByBranchRequest)(nil),  // 0: inventory.warehouse.GetDefaultWarehouseByBranchRequest
	(*GetDefaultWarehouseByBranchResponse)(nil), // 1: inventory.warehouse.GetDefaultWarehouseByBranchResponse
}
var file_proto_inventory_warehouse_warehouse_proto_depIdxs = []int32{
	0, // 0: inventory.warehouse.WarehouseService.GetDefaultWarehouseByBranch:input_type -> inventory.warehouse.GetDefaultWarehouseByBranchRequest
	1, // 1: inventory.warehouse.WarehouseService.GetDefaultWarehouseByBranch:output_type -> inventory.warehouse.GetDefaultWarehouseByBranchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_warehouse_warehouse_proto_init() }
func file_proto_inventory_warehouse_warehouse_proto_init() {
	if File_proto_inventory_warehouse_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_warehouse_warehouse_proto_rawDesc), len(file_proto_inventory_warehouse_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_warehouse_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_inventory_warehouse_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_inventory_warehouse_warehouse_proto_msgTypes,
	}.Build()
	File_proto_inventory_warehouse_warehouse_proto = out.File
	file_proto_inventory_warehouse_warehouse_proto_goTypes = nil
	file_proto_inventory_warehouse_warehouse_proto_depIdxs = nil
}
