// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/customer/customer_type/customer_type.proto

package customertypepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerTypesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerTypesByIDsRequest) Reset() {
	*x = GetCustomerTypesByIDsRequest{}
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerTypesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerTypesByIDsRequest) ProtoMessage() {}

func (x *GetCustomerTypesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerTypesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerTypesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_type_customer_type_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerTypesByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CustomerTypeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerTypeItem) Reset() {
	*x = CustomerTypeItem{}
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerTypeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerTypeItem) ProtoMessage() {}

func (x *CustomerTypeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerTypeItem.ProtoReflect.Descriptor instead.
func (*CustomerTypeItem) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_type_customer_type_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerTypeItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CustomerTypeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCustomerTypesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Items         []*CustomerTypeItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerTypesByIDsResponse) Reset() {
	*x = GetCustomerTypesByIDsResponse{}
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerTypesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerTypesByIDsResponse) ProtoMessage() {}

func (x *GetCustomerTypesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_type_customer_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerTypesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerTypesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_type_customer_type_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerTypesByIDsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCustomerTypesByIDsResponse) GetItems() []*CustomerTypeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_customer_customer_type_customer_type_proto protoreflect.FileDescriptor

const file_proto_customer_customer_type_customer_type_proto_rawDesc = "" +
	"\n" +
	"0proto/customer/customer_type/customer_type.proto\x12\x16customer.customer_type\"0\n" +
	"\x1cGetCustomerTypesByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"6\n" +
	"\x10CustomerTypeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"y\n" +
	"\x1dGetCustomerTypesByIDsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x05items\x18\x02 \x03(\v2(.customer.customer_type.CustomerTypeItemR\x05items2\x9c\x01\n" +
	"\x13CustomerTypeService\x12\x84\x01\n" +
	"\x15GetCustomerTypesByIDs\x124.customer.customer_type.GetCustomerTypesByIDsRequest\x1a5.customer.customer_type.GetCustomerTypesByIDsResponseBLZJgithub.com/InBitGT/proto-definitions/customer/customer_type;customertypepbb\x06proto3"

var (
	file_proto_customer_customer_type_customer_type_proto_rawDescOnce sync.Once
	file_proto_customer_customer_type_customer_type_proto_rawDescData []byte
)

func file_proto_customer_customer_type_customer_type_proto_rawDescGZIP() []byte {
	file_proto_customer_customer_type_customer_type_proto_rawDescOnce.Do(func() {
		file_proto_customer_customer_type_customer_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_customer_customer_type_customer_type_proto_rawDesc), len(file_proto_customer_customer_type_customer_type_proto_rawDesc)))
	})
	return file_proto_customer_customer_type_customer_type_proto_rawDescData
}

var file_proto_customer_customer_type_customer_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_customer_customer_type_customer_type_proto_goTypes = []any{
	(*GetCustomerTypesByIDsRequest)(nil),  // 0: customer.customer_type.GetCustomerTypesByIDsRequest
	(*CustomerTypeItem)(nil),              // 1: customer.customer_type.CustomerTypeItem
	(*GetCustomerTypesByIDsResponse)(nil), // 2: customer.customer_type.GetCustomerTypesByIDsResponse
}
var file_proto_customer_customer_type_customer_type_proto_depIdxs = []int32{
	1, // 0: customer.customer_type.GetCustomerTypesByIDsResponse.items:type_name -> customer.customer_type.CustomerTypeItem
	0, // 1: customer.customer_type.CustomerTypeService.GetCustomerTypesByIDs:input_type -> customer.customer_type.GetCustomerTypesByIDsRequest
	2, // 2: customer.customer_type.CustomerTypeService.GetCustomerTypesByIDs:output_type -> customer.customer_type.GetCustomerTypesByIDsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_customer_customer_type_customer_type_proto_init() }
func file_proto_customer_customer_type_customer_type_proto_init() {
	if File_proto_customer_customer_type_customer_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_customer_customer_type_customer_type_proto_rawDesc), len(file_proto_customer_customer_type_customer_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_customer_customer_type_customer_type_proto_goTypes,
		DependencyIndexes: file_proto_customer_customer_type_customer_type_proto_depIdxs,
		MessageInfos:      file_proto_customer_customer_type_customer_type_proto_msgTypes,
	}.Build()
	File_proto_customer_customer_type_customer_type_proto = out.File
	file_proto_customer_customer_type_customer_type_proto_goTypes = nil
	file_proto_customer_customer_type_customer_type_proto_depIdxs = nil
}
