// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/customer/customer_type/customer_type.proto

package customertypepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerTypeService_GetCustomerTypesByIDs_FullMethodName = "/customer.customer_type.CustomerTypeService/GetCustomerTypesByIDs"
)

// CustomerTypeServiceClient is the client API for CustomerTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerTypeServiceClient interface {
	GetCustomerTypesByIDs(ctx context.Context, in *GetCustomerTypesByIDsRequest, opts ...grpc.CallOption) (*GetCustomerTypesByIDsResponse, error)
}

type customerTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerTypeServiceClient(cc grpc.ClientConnInterface) CustomerTypeServiceClient {
	return &customerTypeServiceClient{cc}
}

func (c *customerTypeServiceClient) GetCustomerTypesByIDs(ctx context.Context, in *GetCustomerTypesByIDsRequest, opts ...grpc.CallOption) (*GetCustomerTypesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerTypesByIDsResponse)
	err := c.cc.Invoke(ctx, CustomerTypeService_GetCustomerTypesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerTypeServiceServer is the server API for CustomerTypeService service.
// All implementations must embed UnimplementedCustomerTypeServiceServer
// for forward compatibility.
type CustomerTypeServiceServer interface {
	GetCustomerTypesByIDs(context.Context, *GetCustomerTypesByIDsRequest) (*GetCustomerTypesByIDsResponse, error)
	mustEmbedUnimplementedCustomerTypeServiceServer()
}

// UnimplementedCustomerTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerTypeServiceServer struct{}

func (UnimplementedCustomerTypeServiceServer) GetCustomerTypesByIDs(context.Context, *GetCustomerTypesByIDsRequest) (*GetCustomerTypesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerTypesByIDs not implemented")
}
func (UnimplementedCustomerTypeServiceServer) mustEmbedUnimplementedCustomerTypeServiceServer() {}
func (UnimplementedCustomerTypeServiceServer) testEmbeddedByValue()                             {}

// UnsafeCustomerTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerTypeServiceServer will
// result in compilation errors.
type UnsafeCustomerTypeServiceServer interface {
	mustEmbedUnimplementedCustomerTypeServiceServer()
}

func RegisterCustomerTypeServiceServer(s grpc.ServiceRegistrar, srv CustomerTypeServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerTypeService_ServiceDesc, srv)
}

func _CustomerTypeService_GetCustomerTypesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerTypesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerTypeServiceServer).GetCustomerTypesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerTypeService_GetCustomerTypesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerTypeServiceServer).GetCustomerTypesByIDs(ctx, req.(*GetCustomerTypesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerTypeService_ServiceDesc is the grpc.ServiceDesc for CustomerTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.customer_type.CustomerTypeService",
	HandlerType: (*CustomerTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerTypesByIDs",
			Handler:    _CustomerTypeService_GetCustomerTypesByIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/customer/customer_type/customer_type.proto",
}
