// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/payment/plan/plan.proto

package plan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_proto_payment_plan_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_plan_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_plan_plan_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlanRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_proto_payment_plan_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_plan_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_plan_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_proto_payment_plan_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_plan_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_plan_plan_proto_rawDescGZIP(), []int{2}
}

func (x *PlanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PlanResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlanResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_payment_plan_plan_proto protoreflect.FileDescriptor

const file_proto_payment_plan_plan_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/payment/plan/plan.proto\x12\x04plan\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"_\n" +
	"\x11CreatePlanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xc0\x01\n" +
	"\fPlanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt2\x81\x01\n" +
	"\vPlanService\x125\n" +
	"\aGetPlan\x12\x14.plan.GetPlanRequest\x1a\x12.plan.PlanResponse\"\x00\x12;\n" +
	"\n" +
	"CreatePlan\x12\x17.plan.CreatePlanRequest\x1a\x12.plan.PlanResponse\"\x00B3Z1github.com/InBitGT/proto-definitions/payment/planb\x06proto3"

var (
	file_proto_payment_plan_plan_proto_rawDescOnce sync.Once
	file_proto_payment_plan_plan_proto_rawDescData []byte
)

func file_proto_payment_plan_plan_proto_rawDescGZIP() []byte {
	file_proto_payment_plan_plan_proto_rawDescOnce.Do(func() {
		file_proto_payment_plan_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_plan_plan_proto_rawDesc), len(file_proto_payment_plan_plan_proto_rawDesc)))
	})
	return file_proto_payment_plan_plan_proto_rawDescData
}

var file_proto_payment_plan_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_payment_plan_plan_proto_goTypes = []any{
	(*GetPlanRequest)(nil),    // 0: plan.GetPlanRequest
	(*CreatePlanRequest)(nil), // 1: plan.CreatePlanRequest
	(*PlanResponse)(nil),      // 2: plan.PlanResponse
}
var file_proto_payment_plan_plan_proto_depIdxs = []int32{
	0, // 0: plan.PlanService.GetPlan:input_type -> plan.GetPlanRequest
	1, // 1: plan.PlanService.CreatePlan:input_type -> plan.CreatePlanRequest
	2, // 2: plan.PlanService.GetPlan:output_type -> plan.PlanResponse
	2, // 3: plan.PlanService.CreatePlan:output_type -> plan.PlanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payment_plan_plan_proto_init() }
func file_proto_payment_plan_plan_proto_init() {
	if File_proto_payment_plan_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_plan_plan_proto_rawDesc), len(file_proto_payment_plan_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_plan_plan_proto_goTypes,
		DependencyIndexes: file_proto_payment_plan_plan_proto_depIdxs,
		MessageInfos:      file_proto_payment_plan_plan_proto_msgTypes,
	}.Build()
	File_proto_payment_plan_plan_proto = out.File
	file_proto_payment_plan_plan_proto_goTypes = nil
	file_proto_payment_plan_plan_proto_depIdxs = nil
}
