// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/payment/suscription/suscription.proto

package suscription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SuscriptionService_GetSuscription_FullMethodName    = "/suscription.SuscriptionService/GetSuscription"
	SuscriptionService_CreateSuscription_FullMethodName = "/suscription.SuscriptionService/CreateSuscription"
)

// SuscriptionServiceClient is the client API for SuscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuscriptionServiceClient interface {
	GetSuscription(ctx context.Context, in *GetSuscriptionRequest, opts ...grpc.CallOption) (*SuscriptionResponse, error)
	CreateSuscription(ctx context.Context, in *CreateSuscriptionRequest, opts ...grpc.CallOption) (*SuscriptionResponse, error)
}

type suscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuscriptionServiceClient(cc grpc.ClientConnInterface) SuscriptionServiceClient {
	return &suscriptionServiceClient{cc}
}

func (c *suscriptionServiceClient) GetSuscription(ctx context.Context, in *GetSuscriptionRequest, opts ...grpc.CallOption) (*SuscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuscriptionResponse)
	err := c.cc.Invoke(ctx, SuscriptionService_GetSuscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suscriptionServiceClient) CreateSuscription(ctx context.Context, in *CreateSuscriptionRequest, opts ...grpc.CallOption) (*SuscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuscriptionResponse)
	err := c.cc.Invoke(ctx, SuscriptionService_CreateSuscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuscriptionServiceServer is the server API for SuscriptionService service.
// All implementations must embed UnimplementedSuscriptionServiceServer
// for forward compatibility.
type SuscriptionServiceServer interface {
	GetSuscription(context.Context, *GetSuscriptionRequest) (*SuscriptionResponse, error)
	CreateSuscription(context.Context, *CreateSuscriptionRequest) (*SuscriptionResponse, error)
	mustEmbedUnimplementedSuscriptionServiceServer()
}

// UnimplementedSuscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuscriptionServiceServer struct{}

func (UnimplementedSuscriptionServiceServer) GetSuscription(context.Context, *GetSuscriptionRequest) (*SuscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuscription not implemented")
}
func (UnimplementedSuscriptionServiceServer) CreateSuscription(context.Context, *CreateSuscriptionRequest) (*SuscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSuscription not implemented")
}
func (UnimplementedSuscriptionServiceServer) mustEmbedUnimplementedSuscriptionServiceServer() {}
func (UnimplementedSuscriptionServiceServer) testEmbeddedByValue()                            {}

// UnsafeSuscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuscriptionServiceServer will
// result in compilation errors.
type UnsafeSuscriptionServiceServer interface {
	mustEmbedUnimplementedSuscriptionServiceServer()
}

func RegisterSuscriptionServiceServer(s grpc.ServiceRegistrar, srv SuscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedSuscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuscriptionService_ServiceDesc, srv)
}

func _SuscriptionService_GetSuscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuscriptionServiceServer).GetSuscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuscriptionService_GetSuscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuscriptionServiceServer).GetSuscription(ctx, req.(*GetSuscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuscriptionService_CreateSuscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSuscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuscriptionServiceServer).CreateSuscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuscriptionService_CreateSuscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuscriptionServiceServer).CreateSuscription(ctx, req.(*CreateSuscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SuscriptionService_ServiceDesc is the grpc.ServiceDesc for SuscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "suscription.SuscriptionService",
	HandlerType: (*SuscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuscription",
			Handler:    _SuscriptionService_GetSuscription_Handler,
		},
		{
			MethodName: "CreateSuscription",
			Handler:    _SuscriptionService_CreateSuscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/suscription/suscription.proto",
}
