// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/product_price/product_price.proto

package productpricepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePriceRequest) Reset() {
	*x = CreatePriceRequest{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceRequest) ProtoMessage() {}

func (x *CreatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceRequest.ProtoReflect.Descriptor instead.
func (*CreatePriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePriceRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreatePriceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePriceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PriceId       uint64                 `protobuf:"varint,2,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePriceResponse) Reset() {
	*x = CreatePriceResponse{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceResponse) ProtoMessage() {}

func (x *CreatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceResponse.ProtoReflect.Descriptor instead.
func (*CreatePriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePriceResponse) GetPriceId() uint64 {
	if x != nil {
		return x.PriceId
	}
	return 0
}

func (x *CreatePriceResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPriceByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceByProductIDRequest) Reset() {
	*x = GetPriceByProductIDRequest{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceByProductIDRequest) ProtoMessage() {}

func (x *GetPriceByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetPriceByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{2}
}

func (x *GetPriceByProductIDRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetPriceByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PriceId       uint64                 `protobuf:"varint,2,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IsBase        bool                   `protobuf:"varint,5,opt,name=is_base,json=isBase,proto3" json:"is_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceByProductIDResponse) Reset() {
	*x = GetPriceByProductIDResponse{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceByProductIDResponse) ProtoMessage() {}

func (x *GetPriceByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetPriceByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{3}
}

func (x *GetPriceByProductIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPriceByProductIDResponse) GetPriceId() uint64 {
	if x != nil {
		return x.PriceId
	}
	return 0
}

func (x *GetPriceByProductIDResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPriceByProductIDResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPriceByProductIDResponse) GetIsBase() bool {
	if x != nil {
		return x.IsBase
	}
	return false
}

type PriceCustomerTypeItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerTypeId uint64                 `protobuf:"varint,1,opt,name=customer_type_id,json=customerTypeId,proto3" json:"customer_type_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceCustomerTypeItem) Reset() {
	*x = PriceCustomerTypeItem{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceCustomerTypeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceCustomerTypeItem) ProtoMessage() {}

func (x *PriceCustomerTypeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceCustomerTypeItem.ProtoReflect.Descriptor instead.
func (*PriceCustomerTypeItem) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{4}
}

func (x *PriceCustomerTypeItem) GetCustomerTypeId() uint64 {
	if x != nil {
		return x.CustomerTypeId
	}
	return 0
}

func (x *PriceCustomerTypeItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PriceCustomerTypeItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePriceCustomerTypeRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ProductId     uint64                   `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Items         []*PriceCustomerTypeItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePriceCustomerTypeRequest) Reset() {
	*x = CreatePriceCustomerTypeRequest{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceCustomerTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceCustomerTypeRequest) ProtoMessage() {}

func (x *CreatePriceCustomerTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceCustomerTypeRequest.ProtoReflect.Descriptor instead.
func (*CreatePriceCustomerTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePriceCustomerTypeRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreatePriceCustomerTypeRequest) GetItems() []*PriceCustomerTypeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePriceCustomerTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePriceCustomerTypeResponse) Reset() {
	*x = CreatePriceCustomerTypeResponse{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceCustomerTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceCustomerTypeResponse) ProtoMessage() {}

func (x *CreatePriceCustomerTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceCustomerTypeResponse.ProtoReflect.Descriptor instead.
func (*CreatePriceCustomerTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePriceCustomerTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePriceCustomerTypeResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

type GetPriceCustomerTypesByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceCustomerTypesByProductIDRequest) Reset() {
	*x = GetPriceCustomerTypesByProductIDRequest{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceCustomerTypesByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceCustomerTypesByProductIDRequest) ProtoMessage() {}

func (x *GetPriceCustomerTypesByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceCustomerTypesByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetPriceCustomerTypesByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{7}
}

func (x *GetPriceCustomerTypesByProductIDRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type PriceCustomerTypeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerTypeId uint64                 `protobuf:"varint,2,opt,name=customer_type_id,json=customerTypeId,proto3" json:"customer_type_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceCustomerTypeResult) Reset() {
	*x = PriceCustomerTypeResult{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceCustomerTypeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceCustomerTypeResult) ProtoMessage() {}

func (x *PriceCustomerTypeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceCustomerTypeResult.ProtoReflect.Descriptor instead.
func (*PriceCustomerTypeResult) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{8}
}

func (x *PriceCustomerTypeResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PriceCustomerTypeResult) GetCustomerTypeId() uint64 {
	if x != nil {
		return x.CustomerTypeId
	}
	return 0
}

func (x *PriceCustomerTypeResult) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PriceCustomerTypeResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPriceCustomerTypesByProductIDResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Success       bool                       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Items         []*PriceCustomerTypeResult `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceCustomerTypesByProductIDResponse) Reset() {
	*x = GetPriceCustomerTypesByProductIDResponse{}
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceCustomerTypesByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceCustomerTypesByProductIDResponse) ProtoMessage() {}

func (x *GetPriceCustomerTypesByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_price_product_price_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceCustomerTypesByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetPriceCustomerTypesByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_price_product_price_proto_rawDescGZIP(), []int{9}
}

func (x *GetPriceCustomerTypesByProductIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPriceCustomerTypesByProductIDResponse) GetItems() []*PriceCustomerTypeResult {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_menu_product_price_product_price_proto protoreflect.FileDescriptor

const file_proto_menu_product_price_product_price_proto_rawDesc = "" +
	"\n" +
	",proto/menu/product_price/product_price.proto\x12\x12menu.product_price\"g\n" +
	"\x12CreatePriceRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"~\n" +
	"\x13CreatePriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bprice_id\x18\x02 \x01(\x04R\apriceId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\";\n" +
	"\x1aGetPriceByProductIDRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\x9f\x01\n" +
	"\x1bGetPriceByProductIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bprice_id\x18\x02 \x01(\x04R\apriceId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_base\x18\x05 \x01(\bR\x06isBase\"u\n" +
	"\x15PriceCustomerTypeItem\x12(\n" +
	"\x10customer_type_id\x18\x01 \x01(\x04R\x0ecustomerTypeId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x80\x01\n" +
	"\x1eCreatePriceCustomerTypeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).menu.product_price.PriceCustomerTypeItemR\x05items\"U\n" +
	"\x1fCreatePriceCustomerTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\"H\n" +
	"'GetPriceCustomerTypesByProductIDRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\x87\x01\n" +
	"\x17PriceCustomerTypeResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x10customer_type_id\x18\x02 \x01(\x04R\x0ecustomerTypeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x87\x01\n" +
	"(GetPriceCustomerTypesByProductIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12A\n" +
	"\x05items\x18\x02 \x03(\v2+.menu.product_price.PriceCustomerTypeResultR\x05items2\x92\x04\n" +
	"\x13ProductPriceService\x12^\n" +
	"\vCreatePrice\x12&.menu.product_price.CreatePriceRequest\x1a'.menu.product_price.CreatePriceResponse\x12v\n" +
	"\x13GetPriceByProductID\x12..menu.product_price.GetPriceByProductIDRequest\x1a/.menu.product_price.GetPriceByProductIDResponse\x12\x82\x01\n" +
	"\x17CreatePriceCustomerType\x122.menu.product_price.CreatePriceCustomerTypeRequest\x1a3.menu.product_price.CreatePriceCustomerTypeResponse\x12\x9d\x01\n" +
	" GetPriceCustomerTypesByProductID\x12;.menu.product_price.GetPriceCustomerTypesByProductIDRequest\x1a<.menu.product_price.GetPriceCustomerTypesByProductIDResponseBHZFgithub.com/InBitGT/proto-definitions/menu/product_price;productpricepbb\x06proto3"

var (
	file_proto_menu_product_price_product_price_proto_rawDescOnce sync.Once
	file_proto_menu_product_price_product_price_proto_rawDescData []byte
)

func file_proto_menu_product_price_product_price_proto_rawDescGZIP() []byte {
	file_proto_menu_product_price_product_price_proto_rawDescOnce.Do(func() {
		file_proto_menu_product_price_product_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_product_price_product_price_proto_rawDesc), len(file_proto_menu_product_price_product_price_proto_rawDesc)))
	})
	return file_proto_menu_product_price_product_price_proto_rawDescData
}

var file_proto_menu_product_price_product_price_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_menu_product_price_product_price_proto_goTypes = []any{
	(*CreatePriceRequest)(nil),                       // 0: menu.product_price.CreatePriceRequest
	(*CreatePriceResponse)(nil),                      // 1: menu.product_price.CreatePriceResponse
	(*GetPriceByProductIDRequest)(nil),               // 2: menu.product_price.GetPriceByProductIDRequest
	(*GetPriceByProductIDResponse)(nil),              // 3: menu.product_price.GetPriceByProductIDResponse
	(*PriceCustomerTypeItem)(nil),                    // 4: menu.product_price.PriceCustomerTypeItem
	(*CreatePriceCustomerTypeRequest)(nil),           // 5: menu.product_price.CreatePriceCustomerTypeRequest
	(*CreatePriceCustomerTypeResponse)(nil),          // 6: menu.product_price.CreatePriceCustomerTypeResponse
	(*GetPriceCustomerTypesByProductIDRequest)(nil),  // 7: menu.product_price.GetPriceCustomerTypesByProductIDRequest
	(*PriceCustomerTypeResult)(nil),                  // 8: menu.product_price.PriceCustomerTypeResult
	(*GetPriceCustomerTypesByProductIDResponse)(nil), // 9: menu.product_price.GetPriceCustomerTypesByProductIDResponse
}
var file_proto_menu_product_price_product_price_proto_depIdxs = []int32{
	4, // 0: menu.product_price.CreatePriceCustomerTypeRequest.items:type_name -> menu.product_price.PriceCustomerTypeItem
	8, // 1: menu.product_price.GetPriceCustomerTypesByProductIDResponse.items:type_name -> menu.product_price.PriceCustomerTypeResult
	0, // 2: menu.product_price.ProductPriceService.CreatePrice:input_type -> menu.product_price.CreatePriceRequest
	2, // 3: menu.product_price.ProductPriceService.GetPriceByProductID:input_type -> menu.product_price.GetPriceByProductIDRequest
	5, // 4: menu.product_price.ProductPriceService.CreatePriceCustomerType:input_type -> menu.product_price.CreatePriceCustomerTypeRequest
	7, // 5: menu.product_price.ProductPriceService.GetPriceCustomerTypesByProductID:input_type -> menu.product_price.GetPriceCustomerTypesByProductIDRequest
	1, // 6: menu.product_price.ProductPriceService.CreatePrice:output_type -> menu.product_price.CreatePriceResponse
	3, // 7: menu.product_price.ProductPriceService.GetPriceByProductID:output_type -> menu.product_price.GetPriceByProductIDResponse
	6, // 8: menu.product_price.ProductPriceService.CreatePriceCustomerType:output_type -> menu.product_price.CreatePriceCustomerTypeResponse
	9, // 9: menu.product_price.ProductPriceService.GetPriceCustomerTypesByProductID:output_type -> menu.product_price.GetPriceCustomerTypesByProductIDResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_menu_product_price_product_price_proto_init() }
func file_proto_menu_product_price_product_price_proto_init() {
	if File_proto_menu_product_price_product_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_product_price_product_price_proto_rawDesc), len(file_proto_menu_product_price_product_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_product_price_product_price_proto_goTypes,
		DependencyIndexes: file_proto_menu_product_price_product_price_proto_depIdxs,
		MessageInfos:      file_proto_menu_product_price_product_price_proto_msgTypes,
	}.Build()
	File_proto_menu_product_price_product_price_proto = out.File
	file_proto_menu_product_price_product_price_proto_goTypes = nil
	file_proto_menu_product_price_product_price_proto_depIdxs = nil
}
