// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/menu/product_price/product_price.proto

package productpricepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductPriceService_CreatePrice_FullMethodName                      = "/menu.product_price.ProductPriceService/CreatePrice"
	ProductPriceService_GetPriceByProductID_FullMethodName              = "/menu.product_price.ProductPriceService/GetPriceByProductID"
	ProductPriceService_CreatePriceCustomerType_FullMethodName          = "/menu.product_price.ProductPriceService/CreatePriceCustomerType"
	ProductPriceService_GetPriceCustomerTypesByProductID_FullMethodName = "/menu.product_price.ProductPriceService/GetPriceCustomerTypesByProductID"
)

// ProductPriceServiceClient is the client API for ProductPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductPriceServiceClient interface {
	CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*CreatePriceResponse, error)
	GetPriceByProductID(ctx context.Context, in *GetPriceByProductIDRequest, opts ...grpc.CallOption) (*GetPriceByProductIDResponse, error)
	CreatePriceCustomerType(ctx context.Context, in *CreatePriceCustomerTypeRequest, opts ...grpc.CallOption) (*CreatePriceCustomerTypeResponse, error)
	GetPriceCustomerTypesByProductID(ctx context.Context, in *GetPriceCustomerTypesByProductIDRequest, opts ...grpc.CallOption) (*GetPriceCustomerTypesByProductIDResponse, error)
}

type productPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductPriceServiceClient(cc grpc.ClientConnInterface) ProductPriceServiceClient {
	return &productPriceServiceClient{cc}
}

func (c *productPriceServiceClient) CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*CreatePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePriceResponse)
	err := c.cc.Invoke(ctx, ProductPriceService_CreatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productPriceServiceClient) GetPriceByProductID(ctx context.Context, in *GetPriceByProductIDRequest, opts ...grpc.CallOption) (*GetPriceByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductPriceService_GetPriceByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productPriceServiceClient) CreatePriceCustomerType(ctx context.Context, in *CreatePriceCustomerTypeRequest, opts ...grpc.CallOption) (*CreatePriceCustomerTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePriceCustomerTypeResponse)
	err := c.cc.Invoke(ctx, ProductPriceService_CreatePriceCustomerType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productPriceServiceClient) GetPriceCustomerTypesByProductID(ctx context.Context, in *GetPriceCustomerTypesByProductIDRequest, opts ...grpc.CallOption) (*GetPriceCustomerTypesByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceCustomerTypesByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductPriceService_GetPriceCustomerTypesByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductPriceServiceServer is the server API for ProductPriceService service.
// All implementations must embed UnimplementedProductPriceServiceServer
// for forward compatibility.
type ProductPriceServiceServer interface {
	CreatePrice(context.Context, *CreatePriceRequest) (*CreatePriceResponse, error)
	GetPriceByProductID(context.Context, *GetPriceByProductIDRequest) (*GetPriceByProductIDResponse, error)
	CreatePriceCustomerType(context.Context, *CreatePriceCustomerTypeRequest) (*CreatePriceCustomerTypeResponse, error)
	GetPriceCustomerTypesByProductID(context.Context, *GetPriceCustomerTypesByProductIDRequest) (*GetPriceCustomerTypesByProductIDResponse, error)
	mustEmbedUnimplementedProductPriceServiceServer()
}

// UnimplementedProductPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductPriceServiceServer struct{}

func (UnimplementedProductPriceServiceServer) CreatePrice(context.Context, *CreatePriceRequest) (*CreatePriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrice not implemented")
}
func (UnimplementedProductPriceServiceServer) GetPriceByProductID(context.Context, *GetPriceByProductIDRequest) (*GetPriceByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceByProductID not implemented")
}
func (UnimplementedProductPriceServiceServer) CreatePriceCustomerType(context.Context, *CreatePriceCustomerTypeRequest) (*CreatePriceCustomerTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePriceCustomerType not implemented")
}
func (UnimplementedProductPriceServiceServer) GetPriceCustomerTypesByProductID(context.Context, *GetPriceCustomerTypesByProductIDRequest) (*GetPriceCustomerTypesByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceCustomerTypesByProductID not implemented")
}
func (UnimplementedProductPriceServiceServer) mustEmbedUnimplementedProductPriceServiceServer() {}
func (UnimplementedProductPriceServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductPriceServiceServer will
// result in compilation errors.
type UnsafeProductPriceServiceServer interface {
	mustEmbedUnimplementedProductPriceServiceServer()
}

func RegisterProductPriceServiceServer(s grpc.ServiceRegistrar, srv ProductPriceServiceServer) {
	// If the following call panics, it indicates UnimplementedProductPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductPriceService_ServiceDesc, srv)
}

func _ProductPriceService_CreatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPriceServiceServer).CreatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPriceService_CreatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPriceServiceServer).CreatePrice(ctx, req.(*CreatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductPriceService_GetPriceByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPriceServiceServer).GetPriceByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPriceService_GetPriceByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPriceServiceServer).GetPriceByProductID(ctx, req.(*GetPriceByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductPriceService_CreatePriceCustomerType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceCustomerTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPriceServiceServer).CreatePriceCustomerType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPriceService_CreatePriceCustomerType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPriceServiceServer).CreatePriceCustomerType(ctx, req.(*CreatePriceCustomerTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductPriceService_GetPriceCustomerTypesByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceCustomerTypesByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPriceServiceServer).GetPriceCustomerTypesByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPriceService_GetPriceCustomerTypesByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPriceServiceServer).GetPriceCustomerTypesByProductID(ctx, req.(*GetPriceCustomerTypesByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductPriceService_ServiceDesc is the grpc.ServiceDesc for ProductPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menu.product_price.ProductPriceService",
	HandlerType: (*ProductPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrice",
			Handler:    _ProductPriceService_CreatePrice_Handler,
		},
		{
			MethodName: "GetPriceByProductID",
			Handler:    _ProductPriceService_GetPriceByProductID_Handler,
		},
		{
			MethodName: "CreatePriceCustomerType",
			Handler:    _ProductPriceService_CreatePriceCustomerType_Handler,
		},
		{
			MethodName: "GetPriceCustomerTypesByProductID",
			Handler:    _ProductPriceService_GetPriceCustomerTypesByProductID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/menu/product_price/product_price.proto",
}
