// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/product/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CategoryId         uint64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Sku                string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode            string                 `protobuf:"bytes,6,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Brand              string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Type               string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	UnitOfMeasure      string                 `protobuf:"bytes,9,opt,name=unit_of_measure,json=unitOfMeasure,proto3" json:"unit_of_measure,omitempty"`
	AverageCost        float64                `protobuf:"fixed64,10,opt,name=average_cost,json=averageCost,proto3" json:"average_cost,omitempty"`
	RequiresBatch      bool                   `protobuf:"varint,11,opt,name=requires_batch,json=requiresBatch,proto3" json:"requires_batch,omitempty"`
	AvailabilityStatus string                 `protobuf:"bytes,12,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	Picture            string                 `protobuf:"bytes,13,opt,name=picture,proto3" json:"picture,omitempty"`
	IsModifier         bool                   `protobuf:"varint,14,opt,name=is_modifier,json=isModifier,proto3" json:"is_modifier,omitempty"`
	ModifierGroup      string                 `protobuf:"bytes,15,opt,name=modifier_group,json=modifierGroup,proto3" json:"modifier_group,omitempty"`
	ModifierName       string                 `protobuf:"bytes,16,opt,name=modifier_name,json=modifierName,proto3" json:"modifier_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProductRequest) GetUnitOfMeasure() string {
	if x != nil {
		return x.UnitOfMeasure
	}
	return ""
}

func (x *CreateProductRequest) GetAverageCost() float64 {
	if x != nil {
		return x.AverageCost
	}
	return 0
}

func (x *CreateProductRequest) GetRequiresBatch() bool {
	if x != nil {
		return x.RequiresBatch
	}
	return false
}

func (x *CreateProductRequest) GetAvailabilityStatus() string {
	if x != nil {
		return x.AvailabilityStatus
	}
	return ""
}

func (x *CreateProductRequest) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *CreateProductRequest) GetIsModifier() bool {
	if x != nil {
		return x.IsModifier
	}
	return false
}

func (x *CreateProductRequest) GetModifierGroup() string {
	if x != nil {
		return x.ModifierGroup
	}
	return ""
}

func (x *CreateProductRequest) GetModifierName() string {
	if x != nil {
		return x.ModifierName
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProductResponse) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *DeactivateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeactivateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductResponse) Reset() {
	*x = DeactivateProductResponse{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductResponse) ProtoMessage() {}

func (x *DeactivateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductResponse.ProtoReflect.Descriptor instead.
func (*DeactivateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeactivateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,3,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListProductsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListProductsRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ProductResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CategoryId         uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Sku                string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode            string                 `protobuf:"bytes,7,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Brand              string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Type               string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	UnitOfMeasure      string                 `protobuf:"bytes,10,opt,name=unit_of_measure,json=unitOfMeasure,proto3" json:"unit_of_measure,omitempty"`
	AverageCost        float64                `protobuf:"fixed64,11,opt,name=average_cost,json=averageCost,proto3" json:"average_cost,omitempty"`
	RequiresBatch      bool                   `protobuf:"varint,12,opt,name=requires_batch,json=requiresBatch,proto3" json:"requires_batch,omitempty"`
	AvailabilityStatus string                 `protobuf:"bytes,13,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	Picture            string                 `protobuf:"bytes,14,opt,name=picture,proto3" json:"picture,omitempty"`
	Status             bool                   `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	IsModifier         bool                   `protobuf:"varint,16,opt,name=is_modifier,json=isModifier,proto3" json:"is_modifier,omitempty"`
	ModifierGroup      string                 `protobuf:"bytes,17,opt,name=modifier_group,json=modifierGroup,proto3" json:"modifier_group,omitempty"`
	ModifierName       string                 `protobuf:"bytes,18,opt,name=modifier_name,json=modifierName,proto3" json:"modifier_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ProductResponse) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductResponse) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductResponse) GetUnitOfMeasure() string {
	if x != nil {
		return x.UnitOfMeasure
	}
	return ""
}

func (x *ProductResponse) GetAverageCost() float64 {
	if x != nil {
		return x.AverageCost
	}
	return 0
}

func (x *ProductResponse) GetRequiresBatch() bool {
	if x != nil {
		return x.RequiresBatch
	}
	return false
}

func (x *ProductResponse) GetAvailabilityStatus() string {
	if x != nil {
		return x.AvailabilityStatus
	}
	return ""
}

func (x *ProductResponse) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ProductResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ProductResponse) GetIsModifier() bool {
	if x != nil {
		return x.IsModifier
	}
	return false
}

func (x *ProductResponse) GetModifierGroup() string {
	if x != nil {
		return x.ModifierGroup
	}
	return ""
}

func (x *ProductResponse) GetModifierName() string {
	if x != nil {
		return x.ModifierName
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_inventory_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_proto_inventory_product_product_proto protoreflect.FileDescriptor

const file_proto_inventory_product_product_proto_rawDesc = "" +
	"\n" +
	"%proto/inventory/product/product.proto\x12\x11inventory.product\"\x8a\x04\n" +
	"\x14CreateProductRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\x06 \x01(\tR\abarcode\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12&\n" +
	"\x0funit_of_measure\x18\t \x01(\tR\runitOfMeasure\x12!\n" +
	"\faverage_cost\x18\n" +
	" \x01(\x01R\vaverageCost\x12%\n" +
	"\x0erequires_batch\x18\v \x01(\bR\rrequiresBatch\x12/\n" +
	"\x13availability_status\x18\f \x01(\tR\x12availabilityStatus\x12\x18\n" +
	"\apicture\x18\r \x01(\tR\apicture\x12\x1f\n" +
	"\vis_modifier\x18\x0e \x01(\bR\n" +
	"isModifier\x12%\n" +
	"\x0emodifier_group\x18\x0f \x01(\tR\rmodifierGroup\x12#\n" +
	"\rmodifier_name\x18\x10 \x01(\tR\fmodifierName\"P\n" +
	"\x15CreateProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"*\n" +
	"\x18DeactivateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"5\n" +
	"\x19DeactivateProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vonly_active\x18\x03 \x01(\bR\n" +
	"onlyActive\"\xad\x04\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\a \x01(\tR\abarcode\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12&\n" +
	"\x0funit_of_measure\x18\n" +
	" \x01(\tR\runitOfMeasure\x12!\n" +
	"\faverage_cost\x18\v \x01(\x01R\vaverageCost\x12%\n" +
	"\x0erequires_batch\x18\f \x01(\bR\rrequiresBatch\x12/\n" +
	"\x13availability_status\x18\r \x01(\tR\x12availabilityStatus\x12\x18\n" +
	"\apicture\x18\x0e \x01(\tR\apicture\x12\x16\n" +
	"\x06status\x18\x0f \x01(\bR\x06status\x12\x1f\n" +
	"\vis_modifier\x18\x10 \x01(\bR\n" +
	"isModifier\x12%\n" +
	"\x0emodifier_group\x18\x11 \x01(\tR\rmodifierGroup\x12#\n" +
	"\rmodifier_name\x18\x12 \x01(\tR\fmodifierName\"V\n" +
	"\x14ListProductsResponse\x12>\n" +
	"\bproducts\x18\x01 \x03(\v2\".inventory.product.ProductResponseR\bproducts2\xa5\x03\n" +
	"\x0eProductService\x12b\n" +
	"\rCreateProduct\x12'.inventory.product.CreateProductRequest\x1a(.inventory.product.CreateProductResponse\x12^\n" +
	"\x0eGetProductByID\x12(.inventory.product.GetProductByIDRequest\x1a\".inventory.product.ProductResponse\x12n\n" +
	"\x11DeactivateProduct\x12+.inventory.product.DeactivateProductRequest\x1a,.inventory.product.DeactivateProductResponse\x12_\n" +
	"\fListProducts\x12&.inventory.product.ListProductsRequest\x1a'.inventory.product.ListProductsResponseBBZ@github.com/InBitGT/proto-definitions/inventory/product;productpbb\x06proto3"

var (
	file_proto_inventory_product_product_proto_rawDescOnce sync.Once
	file_proto_inventory_product_product_proto_rawDescData []byte
)

func file_proto_inventory_product_product_proto_rawDescGZIP() []byte {
	file_proto_inventory_product_product_proto_rawDescOnce.Do(func() {
		file_proto_inventory_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_product_product_proto_rawDesc), len(file_proto_inventory_product_product_proto_rawDesc)))
	})
	return file_proto_inventory_product_product_proto_rawDescData
}

var file_proto_inventory_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_inventory_product_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil),      // 0: inventory.product.CreateProductRequest
	(*CreateProductResponse)(nil),     // 1: inventory.product.CreateProductResponse
	(*GetProductByIDRequest)(nil),     // 2: inventory.product.GetProductByIDRequest
	(*DeactivateProductRequest)(nil),  // 3: inventory.product.DeactivateProductRequest
	(*DeactivateProductResponse)(nil), // 4: inventory.product.DeactivateProductResponse
	(*ListProductsRequest)(nil),       // 5: inventory.product.ListProductsRequest
	(*ProductResponse)(nil),           // 6: inventory.product.ProductResponse
	(*ListProductsResponse)(nil),      // 7: inventory.product.ListProductsResponse
}
var file_proto_inventory_product_product_proto_depIdxs = []int32{
	6, // 0: inventory.product.ListProductsResponse.products:type_name -> inventory.product.ProductResponse
	0, // 1: inventory.product.ProductService.CreateProduct:input_type -> inventory.product.CreateProductRequest
	2, // 2: inventory.product.ProductService.GetProductByID:input_type -> inventory.product.GetProductByIDRequest
	3, // 3: inventory.product.ProductService.DeactivateProduct:input_type -> inventory.product.DeactivateProductRequest
	5, // 4: inventory.product.ProductService.ListProducts:input_type -> inventory.product.ListProductsRequest
	1, // 5: inventory.product.ProductService.CreateProduct:output_type -> inventory.product.CreateProductResponse
	6, // 6: inventory.product.ProductService.GetProductByID:output_type -> inventory.product.ProductResponse
	4, // 7: inventory.product.ProductService.DeactivateProduct:output_type -> inventory.product.DeactivateProductResponse
	7, // 8: inventory.product.ProductService.ListProducts:output_type -> inventory.product.ListProductsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inventory_product_product_proto_init() }
func file_proto_inventory_product_product_proto_init() {
	if File_proto_inventory_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_product_product_proto_rawDesc), len(file_proto_inventory_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_product_product_proto_goTypes,
		DependencyIndexes: file_proto_inventory_product_product_proto_depIdxs,
		MessageInfos:      file_proto_inventory_product_product_proto_msgTypes,
	}.Build()
	File_proto_inventory_product_product_proto = out.File
	file_proto_inventory_product_product_proto_goTypes = nil
	file_proto_inventory_product_product_proto_depIdxs = nil
}
