// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/inventory/sale_cost/sale_cost.proto

package salecostpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaleCostService_ConsumeAndGetCost_FullMethodName = "/inventory.sale_cost.SaleCostService/ConsumeAndGetCost"
)

// SaleCostServiceClient is the client API for SaleCostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaleCostServiceClient interface {
	ConsumeAndGetCost(ctx context.Context, in *ConsumeAndGetCostRequest, opts ...grpc.CallOption) (*ConsumeAndGetCostResponse, error)
}

type saleCostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaleCostServiceClient(cc grpc.ClientConnInterface) SaleCostServiceClient {
	return &saleCostServiceClient{cc}
}

func (c *saleCostServiceClient) ConsumeAndGetCost(ctx context.Context, in *ConsumeAndGetCostRequest, opts ...grpc.CallOption) (*ConsumeAndGetCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeAndGetCostResponse)
	err := c.cc.Invoke(ctx, SaleCostService_ConsumeAndGetCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleCostServiceServer is the server API for SaleCostService service.
// All implementations must embed UnimplementedSaleCostServiceServer
// for forward compatibility.
type SaleCostServiceServer interface {
	ConsumeAndGetCost(context.Context, *ConsumeAndGetCostRequest) (*ConsumeAndGetCostResponse, error)
	mustEmbedUnimplementedSaleCostServiceServer()
}

// UnimplementedSaleCostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaleCostServiceServer struct{}

func (UnimplementedSaleCostServiceServer) ConsumeAndGetCost(context.Context, *ConsumeAndGetCostRequest) (*ConsumeAndGetCostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeAndGetCost not implemented")
}
func (UnimplementedSaleCostServiceServer) mustEmbedUnimplementedSaleCostServiceServer() {}
func (UnimplementedSaleCostServiceServer) testEmbeddedByValue()                         {}

// UnsafeSaleCostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaleCostServiceServer will
// result in compilation errors.
type UnsafeSaleCostServiceServer interface {
	mustEmbedUnimplementedSaleCostServiceServer()
}

func RegisterSaleCostServiceServer(s grpc.ServiceRegistrar, srv SaleCostServiceServer) {
	// If the following call panics, it indicates UnimplementedSaleCostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaleCostService_ServiceDesc, srv)
}

func _SaleCostService_ConsumeAndGetCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeAndGetCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleCostServiceServer).ConsumeAndGetCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaleCostService_ConsumeAndGetCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleCostServiceServer).ConsumeAndGetCost(ctx, req.(*ConsumeAndGetCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaleCostService_ServiceDesc is the grpc.ServiceDesc for SaleCostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaleCostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.sale_cost.SaleCostService",
	HandlerType: (*SaleCostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumeAndGetCost",
			Handler:    _SaleCostService_ConsumeAndGetCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory/sale_cost/sale_cost.proto",
}
