// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/sale_cost/sale_cost.proto

package salecostpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumptionRequestLine struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IngredientProductId uint64                 `protobuf:"varint,1,opt,name=ingredient_product_id,json=ingredientProductId,proto3" json:"ingredient_product_id,omitempty"`
	Quantity            float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit                string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsumptionRequestLine) Reset() {
	*x = ConsumptionRequestLine{}
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionRequestLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionRequestLine) ProtoMessage() {}

func (x *ConsumptionRequestLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionRequestLine.ProtoReflect.Descriptor instead.
func (*ConsumptionRequestLine) Descriptor() ([]byte, []int) {
	return file_proto_inventory_sale_cost_sale_cost_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumptionRequestLine) GetIngredientProductId() uint64 {
	if x != nil {
		return x.IngredientProductId
	}
	return 0
}

func (x *ConsumptionRequestLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ConsumptionRequestLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type ConsumeAndGetCostRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	WarehouseId   uint64                    `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	UserId        uint64                    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReferenceId   uint64                    `protobuf:"varint,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                    `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	Lines         []*ConsumptionRequestLine `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeAndGetCostRequest) Reset() {
	*x = ConsumeAndGetCostRequest{}
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeAndGetCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeAndGetCostRequest) ProtoMessage() {}

func (x *ConsumeAndGetCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeAndGetCostRequest.ProtoReflect.Descriptor instead.
func (*ConsumeAndGetCostRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_sale_cost_sale_cost_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeAndGetCostRequest) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *ConsumeAndGetCostRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsumeAndGetCostRequest) GetReferenceId() uint64 {
	if x != nil {
		return x.ReferenceId
	}
	return 0
}

func (x *ConsumeAndGetCostRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *ConsumeAndGetCostRequest) GetLines() []*ConsumptionRequestLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ConsumptionResultLine struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IngredientProductId uint64                 `protobuf:"varint,1,opt,name=ingredient_product_id,json=ingredientProductId,proto3" json:"ingredient_product_id,omitempty"`
	Quantity            float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitCost            float64                `protobuf:"fixed64,3,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	SubtotalCost        float64                `protobuf:"fixed64,4,opt,name=subtotal_cost,json=subtotalCost,proto3" json:"subtotal_cost,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsumptionResultLine) Reset() {
	*x = ConsumptionResultLine{}
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionResultLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionResultLine) ProtoMessage() {}

func (x *ConsumptionResultLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionResultLine.ProtoReflect.Descriptor instead.
func (*ConsumptionResultLine) Descriptor() ([]byte, []int) {
	return file_proto_inventory_sale_cost_sale_cost_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumptionResultLine) GetIngredientProductId() uint64 {
	if x != nil {
		return x.IngredientProductId
	}
	return 0
}

func (x *ConsumptionResultLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ConsumptionResultLine) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *ConsumptionResultLine) GetSubtotalCost() float64 {
	if x != nil {
		return x.SubtotalCost
	}
	return 0
}

type ConsumeAndGetCostResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Success       bool                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalCost     float64                  `protobuf:"fixed64,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Lines         []*ConsumptionResultLine `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeAndGetCostResponse) Reset() {
	*x = ConsumeAndGetCostResponse{}
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeAndGetCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeAndGetCostResponse) ProtoMessage() {}

func (x *ConsumeAndGetCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_sale_cost_sale_cost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeAndGetCostResponse.ProtoReflect.Descriptor instead.
func (*ConsumeAndGetCostResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_sale_cost_sale_cost_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeAndGetCostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeAndGetCostResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ConsumeAndGetCostResponse) GetLines() []*ConsumptionResultLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_proto_inventory_sale_cost_sale_cost_proto protoreflect.FileDescriptor

const file_proto_inventory_sale_cost_sale_cost_proto_rawDesc = "" +
	"\n" +
	")proto/inventory/sale_cost/sale_cost.proto\x12\x13inventory.sale_cost\"|\n" +
	"\x16ConsumptionRequestLine\x122\n" +
	"\x15ingredient_product_id\x18\x01 \x01(\x04R\x13ingredientProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"\xe3\x01\n" +
	"\x18ConsumeAndGetCostRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x04R\vwarehouseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\freference_id\x18\x03 \x01(\x04R\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\x12A\n" +
	"\x05lines\x18\x05 \x03(\v2+.inventory.sale_cost.ConsumptionRequestLineR\x05lines\"\xa9\x01\n" +
	"\x15ConsumptionResultLine\x122\n" +
	"\x15ingredient_product_id\x18\x01 \x01(\x04R\x13ingredientProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x1b\n" +
	"\tunit_cost\x18\x03 \x01(\x01R\bunitCost\x12#\n" +
	"\rsubtotal_cost\x18\x04 \x01(\x01R\fsubtotalCost\"\x96\x01\n" +
	"\x19ConsumeAndGetCostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x01R\ttotalCost\x12@\n" +
	"\x05lines\x18\x03 \x03(\v2*.inventory.sale_cost.ConsumptionResultLineR\x05lines2\x85\x01\n" +
	"\x0fSaleCostService\x12r\n" +
	"\x11ConsumeAndGetCost\x12-.inventory.sale_cost.ConsumeAndGetCostRequest\x1a..inventory.sale_cost.ConsumeAndGetCostResponseBEZCgithub.com/InBitGT/proto-definitions/inventory/sale_cost;salecostpbb\x06proto3"

var (
	file_proto_inventory_sale_cost_sale_cost_proto_rawDescOnce sync.Once
	file_proto_inventory_sale_cost_sale_cost_proto_rawDescData []byte
)

func file_proto_inventory_sale_cost_sale_cost_proto_rawDescGZIP() []byte {
	file_proto_inventory_sale_cost_sale_cost_proto_rawDescOnce.Do(func() {
		file_proto_inventory_sale_cost_sale_cost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_sale_cost_sale_cost_proto_rawDesc), len(file_proto_inventory_sale_cost_sale_cost_proto_rawDesc)))
	})
	return file_proto_inventory_sale_cost_sale_cost_proto_rawDescData
}

var file_proto_inventory_sale_cost_sale_cost_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_inventory_sale_cost_sale_cost_proto_goTypes = []any{
	(*ConsumptionRequestLine)(nil),    // 0: inventory.sale_cost.ConsumptionRequestLine
	(*ConsumeAndGetCostRequest)(nil),  // 1: inventory.sale_cost.ConsumeAndGetCostRequest
	(*ConsumptionResultLine)(nil),     // 2: inventory.sale_cost.ConsumptionResultLine
	(*ConsumeAndGetCostResponse)(nil), // 3: inventory.sale_cost.ConsumeAndGetCostResponse
}
var file_proto_inventory_sale_cost_sale_cost_proto_depIdxs = []int32{
	0, // 0: inventory.sale_cost.ConsumeAndGetCostRequest.lines:type_name -> inventory.sale_cost.ConsumptionRequestLine
	2, // 1: inventory.sale_cost.ConsumeAndGetCostResponse.lines:type_name -> inventory.sale_cost.ConsumptionResultLine
	1, // 2: inventory.sale_cost.SaleCostService.ConsumeAndGetCost:input_type -> inventory.sale_cost.ConsumeAndGetCostRequest
	3, // 3: inventory.sale_cost.SaleCostService.ConsumeAndGetCost:output_type -> inventory.sale_cost.ConsumeAndGetCostResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_inventory_sale_cost_sale_cost_proto_init() }
func file_proto_inventory_sale_cost_sale_cost_proto_init() {
	if File_proto_inventory_sale_cost_sale_cost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_sale_cost_sale_cost_proto_rawDesc), len(file_proto_inventory_sale_cost_sale_cost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_sale_cost_sale_cost_proto_goTypes,
		DependencyIndexes: file_proto_inventory_sale_cost_sale_cost_proto_depIdxs,
		MessageInfos:      file_proto_inventory_sale_cost_sale_cost_proto_msgTypes,
	}.Build()
	File_proto_inventory_sale_cost_sale_cost_proto = out.File
	file_proto_inventory_sale_cost_sale_cost_proto_goTypes = nil
	file_proto_inventory_sale_cost_sale_cost_proto_depIdxs = nil
}
