// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/sale_context/sale_context.proto

package salectxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSaleContextRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductVariantId   uint64                 `protobuf:"varint,2,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	ModifierProductIds []uint64               `protobuf:"varint,3,rep,packed,name=modifier_product_ids,json=modifierProductIds,proto3" json:"modifier_product_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSaleContextRequest) Reset() {
	*x = GetSaleContextRequest{}
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleContextRequest) ProtoMessage() {}

func (x *GetSaleContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleContextRequest.ProtoReflect.Descriptor instead.
func (*GetSaleContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_sale_context_sale_context_proto_rawDescGZIP(), []int{0}
}

func (x *GetSaleContextRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetSaleContextRequest) GetProductVariantId() uint64 {
	if x != nil {
		return x.ProductVariantId
	}
	return 0
}

func (x *GetSaleContextRequest) GetModifierProductIds() []uint64 {
	if x != nil {
		return x.ModifierProductIds
	}
	return nil
}

type ModifierSaleContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	ModifierName      string                 `protobuf:"bytes,2,opt,name=modifier_name,json=modifierName,proto3" json:"modifier_name,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,3,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	Quantity          float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifierSaleContext) Reset() {
	*x = ModifierSaleContext{}
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifierSaleContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifierSaleContext) ProtoMessage() {}

func (x *ModifierSaleContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifierSaleContext.ProtoReflect.Descriptor instead.
func (*ModifierSaleContext) Descriptor() ([]byte, []int) {
	return file_proto_menu_sale_context_sale_context_proto_rawDescGZIP(), []int{1}
}

func (x *ModifierSaleContext) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *ModifierSaleContext) GetModifierName() string {
	if x != nil {
		return x.ModifierName
	}
	return ""
}

func (x *ModifierSaleContext) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *ModifierSaleContext) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ConsumptionLine struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IngredientProductId uint64                 `protobuf:"varint,1,opt,name=ingredient_product_id,json=ingredientProductId,proto3" json:"ingredient_product_id,omitempty"`
	Quantity            float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit                string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsumptionLine) Reset() {
	*x = ConsumptionLine{}
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLine) ProtoMessage() {}

func (x *ConsumptionLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLine.ProtoReflect.Descriptor instead.
func (*ConsumptionLine) Descriptor() ([]byte, []int) {
	return file_proto_menu_sale_context_sale_context_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumptionLine) GetIngredientProductId() uint64 {
	if x != nil {
		return x.IngredientProductId
	}
	return 0
}

func (x *ConsumptionLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ConsumptionLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetSaleContextResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Success                bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProductId              uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName            string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	BasePrice              float64                `protobuf:"fixed64,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	ProductVariantId       uint64                 `protobuf:"varint,5,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	VariantName            string                 `protobuf:"bytes,6,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"`
	VariantPriceAdjustment float64                `protobuf:"fixed64,7,opt,name=variant_price_adjustment,json=variantPriceAdjustment,proto3" json:"variant_price_adjustment,omitempty"`
	Modifiers              []*ModifierSaleContext `protobuf:"bytes,8,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	ConsumptionLines       []*ConsumptionLine     `protobuf:"bytes,9,rep,name=consumption_lines,json=consumptionLines,proto3" json:"consumption_lines,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSaleContextResponse) Reset() {
	*x = GetSaleContextResponse{}
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleContextResponse) ProtoMessage() {}

func (x *GetSaleContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_sale_context_sale_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleContextResponse.ProtoReflect.Descriptor instead.
func (*GetSaleContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_sale_context_sale_context_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaleContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSaleContextResponse) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetSaleContextResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *GetSaleContextResponse) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *GetSaleContextResponse) GetProductVariantId() uint64 {
	if x != nil {
		return x.ProductVariantId
	}
	return 0
}

func (x *GetSaleContextResponse) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

func (x *GetSaleContextResponse) GetVariantPriceAdjustment() float64 {
	if x != nil {
		return x.VariantPriceAdjustment
	}
	return 0
}

func (x *GetSaleContextResponse) GetModifiers() []*ModifierSaleContext {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *GetSaleContextResponse) GetConsumptionLines() []*ConsumptionLine {
	if x != nil {
		return x.ConsumptionLines
	}
	return nil
}

var File_proto_menu_sale_context_sale_context_proto protoreflect.FileDescriptor

const file_proto_menu_sale_context_sale_context_proto_rawDesc = "" +
	"\n" +
	"*proto/menu/sale_context/sale_context.proto\x12\x11menu.sale_context\"\x96\x01\n" +
	"\x15GetSaleContextRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12,\n" +
	"\x12product_variant_id\x18\x02 \x01(\x04R\x10productVariantId\x120\n" +
	"\x14modifier_product_ids\x18\x03 \x03(\x04R\x12modifierProductIds\"\xb1\x01\n" +
	"\x13ModifierSaleContext\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\x12#\n" +
	"\rmodifier_name\x18\x02 \x01(\tR\fmodifierName\x12)\n" +
	"\x10price_adjustment\x18\x03 \x01(\x01R\x0fpriceAdjustment\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\"u\n" +
	"\x0fConsumptionLine\x122\n" +
	"\x15ingredient_product_id\x18\x01 \x01(\x04R\x13ingredientProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"\xb5\x03\n" +
	"\x16GetSaleContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"base_price\x18\x04 \x01(\x01R\tbasePrice\x12,\n" +
	"\x12product_variant_id\x18\x05 \x01(\x04R\x10productVariantId\x12!\n" +
	"\fvariant_name\x18\x06 \x01(\tR\vvariantName\x128\n" +
	"\x18variant_price_adjustment\x18\a \x01(\x01R\x16variantPriceAdjustment\x12D\n" +
	"\tmodifiers\x18\b \x03(\v2&.menu.sale_context.ModifierSaleContextR\tmodifiers\x12O\n" +
	"\x11consumption_lines\x18\t \x03(\v2\".menu.sale_context.ConsumptionLineR\x10consumptionLines2{\n" +
	"\x12SaleContextService\x12e\n" +
	"\x0eGetSaleContext\x12(.menu.sale_context.GetSaleContextRequest\x1a).menu.sale_context.GetSaleContextResponseBBZ@github.com/InBitGT/proto-definitions/menu/sale_context;salectxpbb\x06proto3"

var (
	file_proto_menu_sale_context_sale_context_proto_rawDescOnce sync.Once
	file_proto_menu_sale_context_sale_context_proto_rawDescData []byte
)

func file_proto_menu_sale_context_sale_context_proto_rawDescGZIP() []byte {
	file_proto_menu_sale_context_sale_context_proto_rawDescOnce.Do(func() {
		file_proto_menu_sale_context_sale_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_sale_context_sale_context_proto_rawDesc), len(file_proto_menu_sale_context_sale_context_proto_rawDesc)))
	})
	return file_proto_menu_sale_context_sale_context_proto_rawDescData
}

var file_proto_menu_sale_context_sale_context_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_menu_sale_context_sale_context_proto_goTypes = []any{
	(*GetSaleContextRequest)(nil),  // 0: menu.sale_context.GetSaleContextRequest
	(*ModifierSaleContext)(nil),    // 1: menu.sale_context.ModifierSaleContext
	(*ConsumptionLine)(nil),        // 2: menu.sale_context.ConsumptionLine
	(*GetSaleContextResponse)(nil), // 3: menu.sale_context.GetSaleContextResponse
}
var file_proto_menu_sale_context_sale_context_proto_depIdxs = []int32{
	1, // 0: menu.sale_context.GetSaleContextResponse.modifiers:type_name -> menu.sale_context.ModifierSaleContext
	2, // 1: menu.sale_context.GetSaleContextResponse.consumption_lines:type_name -> menu.sale_context.ConsumptionLine
	0, // 2: menu.sale_context.SaleContextService.GetSaleContext:input_type -> menu.sale_context.GetSaleContextRequest
	3, // 3: menu.sale_context.SaleContextService.GetSaleContext:output_type -> menu.sale_context.GetSaleContextResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_menu_sale_context_sale_context_proto_init() }
func file_proto_menu_sale_context_sale_context_proto_init() {
	if File_proto_menu_sale_context_sale_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_sale_context_sale_context_proto_rawDesc), len(file_proto_menu_sale_context_sale_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_sale_context_sale_context_proto_goTypes,
		DependencyIndexes: file_proto_menu_sale_context_sale_context_proto_depIdxs,
		MessageInfos:      file_proto_menu_sale_context_sale_context_proto_msgTypes,
	}.Build()
	File_proto_menu_sale_context_sale_context_proto = out.File
	file_proto_menu_sale_context_sale_context_proto_goTypes = nil
	file_proto_menu_sale_context_sale_context_proto_depIdxs = nil
}
