// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/pos_context/pos_context.proto

package posctxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPOSContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductIds     []uint64               `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	TenantId       uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CustomerTypeId uint64                 `protobuf:"varint,3,opt,name=customer_type_id,json=customerTypeId,proto3" json:"customer_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPOSContextRequest) Reset() {
	*x = GetPOSContextRequest{}
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPOSContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPOSContextRequest) ProtoMessage() {}

func (x *GetPOSContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPOSContextRequest.ProtoReflect.Descriptor instead.
func (*GetPOSContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_pos_context_pos_context_proto_rawDescGZIP(), []int{0}
}

func (x *GetPOSContextRequest) GetProductIds() []uint64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *GetPOSContextRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetPOSContextRequest) GetCustomerTypeId() uint64 {
	if x != nil {
		return x.CustomerTypeId
	}
	return 0
}

type POSProductContext struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProductId             uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	BasePrice             float64                `protobuf:"fixed64,2,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Currency              string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	HasPromotion          bool                   `protobuf:"varint,4,opt,name=has_promotion,json=hasPromotion,proto3" json:"has_promotion,omitempty"`
	PromotionId           uint64                 `protobuf:"varint,5,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	PromotionName         string                 `protobuf:"bytes,6,opt,name=promotion_name,json=promotionName,proto3" json:"promotion_name,omitempty"`
	PromotionDiscountType string                 `protobuf:"bytes,7,opt,name=promotion_discount_type,json=promotionDiscountType,proto3" json:"promotion_discount_type,omitempty"`
	PromotionValue        float64                `protobuf:"fixed64,8,opt,name=promotion_value,json=promotionValue,proto3" json:"promotion_value,omitempty"`
	HasCustomerTypePrice  bool                   `protobuf:"varint,9,opt,name=has_customer_type_price,json=hasCustomerTypePrice,proto3" json:"has_customer_type_price,omitempty"`
	CustomerTypePrice     float64                `protobuf:"fixed64,10,opt,name=customer_type_price,json=customerTypePrice,proto3" json:"customer_type_price,omitempty"`
	HasWholesale          bool                   `protobuf:"varint,11,opt,name=has_wholesale,json=hasWholesale,proto3" json:"has_wholesale,omitempty"`
	WholesaleMinQty       float64                `protobuf:"fixed64,12,opt,name=wholesale_min_qty,json=wholesaleMinQty,proto3" json:"wholesale_min_qty,omitempty"`
	WholesaleDiscountPct  float64                `protobuf:"fixed64,13,opt,name=wholesale_discount_pct,json=wholesaleDiscountPct,proto3" json:"wholesale_discount_pct,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *POSProductContext) Reset() {
	*x = POSProductContext{}
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POSProductContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POSProductContext) ProtoMessage() {}

func (x *POSProductContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POSProductContext.ProtoReflect.Descriptor instead.
func (*POSProductContext) Descriptor() ([]byte, []int) {
	return file_proto_menu_pos_context_pos_context_proto_rawDescGZIP(), []int{1}
}

func (x *POSProductContext) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *POSProductContext) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *POSProductContext) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *POSProductContext) GetHasPromotion() bool {
	if x != nil {
		return x.HasPromotion
	}
	return false
}

func (x *POSProductContext) GetPromotionId() uint64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *POSProductContext) GetPromotionName() string {
	if x != nil {
		return x.PromotionName
	}
	return ""
}

func (x *POSProductContext) GetPromotionDiscountType() string {
	if x != nil {
		return x.PromotionDiscountType
	}
	return ""
}

func (x *POSProductContext) GetPromotionValue() float64 {
	if x != nil {
		return x.PromotionValue
	}
	return 0
}

func (x *POSProductContext) GetHasCustomerTypePrice() bool {
	if x != nil {
		return x.HasCustomerTypePrice
	}
	return false
}

func (x *POSProductContext) GetCustomerTypePrice() float64 {
	if x != nil {
		return x.CustomerTypePrice
	}
	return 0
}

func (x *POSProductContext) GetHasWholesale() bool {
	if x != nil {
		return x.HasWholesale
	}
	return false
}

func (x *POSProductContext) GetWholesaleMinQty() float64 {
	if x != nil {
		return x.WholesaleMinQty
	}
	return 0
}

func (x *POSProductContext) GetWholesaleDiscountPct() float64 {
	if x != nil {
		return x.WholesaleDiscountPct
	}
	return 0
}

type GetPOSContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Products      []*POSProductContext   `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPOSContextResponse) Reset() {
	*x = GetPOSContextResponse{}
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPOSContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPOSContextResponse) ProtoMessage() {}

func (x *GetPOSContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_pos_context_pos_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPOSContextResponse.ProtoReflect.Descriptor instead.
func (*GetPOSContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_pos_context_pos_context_proto_rawDescGZIP(), []int{2}
}

func (x *GetPOSContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPOSContextResponse) GetProducts() []*POSProductContext {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_proto_menu_pos_context_pos_context_proto protoreflect.FileDescriptor

const file_proto_menu_pos_context_pos_context_proto_rawDesc = "" +
	"\n" +
	"(proto/menu/pos_context/pos_context.proto\x12\x10menu.pos_context\"~\n" +
	"\x14GetPOSContextRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x04R\n" +
	"productIds\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12(\n" +
	"\x10customer_type_id\x18\x03 \x01(\x04R\x0ecustomerTypeId\"\xab\x04\n" +
	"\x11POSProductContext\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1d\n" +
	"\n" +
	"base_price\x18\x02 \x01(\x01R\tbasePrice\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12#\n" +
	"\rhas_promotion\x18\x04 \x01(\bR\fhasPromotion\x12!\n" +
	"\fpromotion_id\x18\x05 \x01(\x04R\vpromotionId\x12%\n" +
	"\x0epromotion_name\x18\x06 \x01(\tR\rpromotionName\x126\n" +
	"\x17promotion_discount_type\x18\a \x01(\tR\x15promotionDiscountType\x12'\n" +
	"\x0fpromotion_value\x18\b \x01(\x01R\x0epromotionValue\x125\n" +
	"\x17has_customer_type_price\x18\t \x01(\bR\x14hasCustomerTypePrice\x12.\n" +
	"\x13customer_type_price\x18\n" +
	" \x01(\x01R\x11customerTypePrice\x12#\n" +
	"\rhas_wholesale\x18\v \x01(\bR\fhasWholesale\x12*\n" +
	"\x11wholesale_min_qty\x18\f \x01(\x01R\x0fwholesaleMinQty\x124\n" +
	"\x16wholesale_discount_pct\x18\r \x01(\x01R\x14wholesaleDiscountPct\"r\n" +
	"\x15GetPOSContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\bproducts\x18\x02 \x03(\v2#.menu.pos_context.POSProductContextR\bproducts2u\n" +
	"\x11POSContextService\x12`\n" +
	"\rGetPOSContext\x12&.menu.pos_context.GetPOSContextRequest\x1a'.menu.pos_context.GetPOSContextResponseB@Z>github.com/InBitGT/proto-definitions/menu/pos_context;posctxpbb\x06proto3"

var (
	file_proto_menu_pos_context_pos_context_proto_rawDescOnce sync.Once
	file_proto_menu_pos_context_pos_context_proto_rawDescData []byte
)

func file_proto_menu_pos_context_pos_context_proto_rawDescGZIP() []byte {
	file_proto_menu_pos_context_pos_context_proto_rawDescOnce.Do(func() {
		file_proto_menu_pos_context_pos_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_pos_context_pos_context_proto_rawDesc), len(file_proto_menu_pos_context_pos_context_proto_rawDesc)))
	})
	return file_proto_menu_pos_context_pos_context_proto_rawDescData
}

var file_proto_menu_pos_context_pos_context_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_menu_pos_context_pos_context_proto_goTypes = []any{
	(*GetPOSContextRequest)(nil),  // 0: menu.pos_context.GetPOSContextRequest
	(*POSProductContext)(nil),     // 1: menu.pos_context.POSProductContext
	(*GetPOSContextResponse)(nil), // 2: menu.pos_context.GetPOSContextResponse
}
var file_proto_menu_pos_context_pos_context_proto_depIdxs = []int32{
	1, // 0: menu.pos_context.GetPOSContextResponse.products:type_name -> menu.pos_context.POSProductContext
	0, // 1: menu.pos_context.POSContextService.GetPOSContext:input_type -> menu.pos_context.GetPOSContextRequest
	2, // 2: menu.pos_context.POSContextService.GetPOSContext:output_type -> menu.pos_context.GetPOSContextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_menu_pos_context_pos_context_proto_init() }
func file_proto_menu_pos_context_pos_context_proto_init() {
	if File_proto_menu_pos_context_pos_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_pos_context_pos_context_proto_rawDesc), len(file_proto_menu_pos_context_pos_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_pos_context_pos_context_proto_goTypes,
		DependencyIndexes: file_proto_menu_pos_context_pos_context_proto_depIdxs,
		MessageInfos:      file_proto_menu_pos_context_pos_context_proto_msgTypes,
	}.Build()
	File_proto_menu_pos_context_pos_context_proto = out.File
	file_proto_menu_pos_context_pos_context_proto_goTypes = nil
	file_proto_menu_pos_context_pos_context_proto_depIdxs = nil
}
