// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/menu/pos_context/pos_context.proto

package posctxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	POSContextService_GetPOSContext_FullMethodName = "/menu.pos_context.POSContextService/GetPOSContext"
)

// POSContextServiceClient is the client API for POSContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type POSContextServiceClient interface {
	GetPOSContext(ctx context.Context, in *GetPOSContextRequest, opts ...grpc.CallOption) (*GetPOSContextResponse, error)
}

type pOSContextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPOSContextServiceClient(cc grpc.ClientConnInterface) POSContextServiceClient {
	return &pOSContextServiceClient{cc}
}

func (c *pOSContextServiceClient) GetPOSContext(ctx context.Context, in *GetPOSContextRequest, opts ...grpc.CallOption) (*GetPOSContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPOSContextResponse)
	err := c.cc.Invoke(ctx, POSContextService_GetPOSContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// POSContextServiceServer is the server API for POSContextService service.
// All implementations must embed UnimplementedPOSContextServiceServer
// for forward compatibility.
type POSContextServiceServer interface {
	GetPOSContext(context.Context, *GetPOSContextRequest) (*GetPOSContextResponse, error)
	mustEmbedUnimplementedPOSContextServiceServer()
}

// UnimplementedPOSContextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPOSContextServiceServer struct{}

func (UnimplementedPOSContextServiceServer) GetPOSContext(context.Context, *GetPOSContextRequest) (*GetPOSContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPOSContext not implemented")
}
func (UnimplementedPOSContextServiceServer) mustEmbedUnimplementedPOSContextServiceServer() {}
func (UnimplementedPOSContextServiceServer) testEmbeddedByValue()                           {}

// UnsafePOSContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to POSContextServiceServer will
// result in compilation errors.
type UnsafePOSContextServiceServer interface {
	mustEmbedUnimplementedPOSContextServiceServer()
}

func RegisterPOSContextServiceServer(s grpc.ServiceRegistrar, srv POSContextServiceServer) {
	// If the following call panics, it indicates UnimplementedPOSContextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&POSContextService_ServiceDesc, srv)
}

func _POSContextService_GetPOSContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPOSContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSContextServiceServer).GetPOSContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSContextService_GetPOSContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSContextServiceServer).GetPOSContext(ctx, req.(*GetPOSContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// POSContextService_ServiceDesc is the grpc.ServiceDesc for POSContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var POSContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menu.pos_context.POSContextService",
	HandlerType: (*POSContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPOSContext",
			Handler:    _POSContextService_GetPOSContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/menu/pos_context/pos_context.proto",
}
