// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user/users/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_proto_user_users_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_users_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_users_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_proto_user_users_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_users_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_users_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,5,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	FirstName     string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RoleId        uint64                 `protobuf:"varint,8,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,9,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthResponse) Reset() {
	*x = UserAuthResponse{}
	mi := &file_proto_user_users_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResponse) ProtoMessage() {}

func (x *UserAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_users_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResponse.ProtoReflect.Descriptor instead.
func (*UserAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_users_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAuthResponse) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UserAuthResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserAuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAuthResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserAuthResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserAuthResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserAuthResponse) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserAuthResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserAuthResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserAuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_user_users_user_proto protoreflect.FileDescriptor

const file_proto_user_users_user_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/user/users/user.proto\x12\x04user\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xbd\x02\n" +
	"\x10UserAuthResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x05 \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x17\n" +
	"\arole_id\x18\b \x01(\x04R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\t \x01(\tR\broleName\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status2\x95\x01\n" +
	"\vUserService\x12E\n" +
	"\x0eGetUserByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x16.user.UserAuthResponse\x12?\n" +
	"\vGetUserByID\x12\x18.user.GetUserByIDRequest\x1a\x16.user.UserAuthResponseB+Z)github.com/InBitGT/proto-definitions/userb\x06proto3"

var (
	file_proto_user_users_user_proto_rawDescOnce sync.Once
	file_proto_user_users_user_proto_rawDescData []byte
)

func file_proto_user_users_user_proto_rawDescGZIP() []byte {
	file_proto_user_users_user_proto_rawDescOnce.Do(func() {
		file_proto_user_users_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_users_user_proto_rawDesc), len(file_proto_user_users_user_proto_rawDesc)))
	})
	return file_proto_user_users_user_proto_rawDescData
}

var file_proto_user_users_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_users_user_proto_goTypes = []any{
	(*GetUserByEmailRequest)(nil), // 0: user.GetUserByEmailRequest
	(*GetUserByIDRequest)(nil),    // 1: user.GetUserByIDRequest
	(*UserAuthResponse)(nil),      // 2: user.UserAuthResponse
}
var file_proto_user_users_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.GetUserByEmail:input_type -> user.GetUserByEmailRequest
	1, // 1: user.UserService.GetUserByID:input_type -> user.GetUserByIDRequest
	2, // 2: user.UserService.GetUserByEmail:output_type -> user.UserAuthResponse
	2, // 3: user.UserService.GetUserByID:output_type -> user.UserAuthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_users_user_proto_init() }
func file_proto_user_users_user_proto_init() {
	if File_proto_user_users_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_users_user_proto_rawDesc), len(file_proto_user_users_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_users_user_proto_goTypes,
		DependencyIndexes: file_proto_user_users_user_proto_depIdxs,
		MessageInfos:      file_proto_user_users_user_proto_msgTypes,
	}.Build()
	File_proto_user_users_user_proto = out.File
	file_proto_user_users_user_proto_goTypes = nil
	file_proto_user_users_user_proto_depIdxs = nil
}
