// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/menu/product_modifier/product_modifier.proto

package productmodifierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductModifierService_CreateProductModifier_FullMethodName                = "/menu.product_modifier.ProductModifierService/CreateProductModifier"
	ProductModifierService_GetProductModifierByProductID_FullMethodName        = "/menu.product_modifier.ProductModifierService/GetProductModifierByProductID"
	ProductModifierService_UpdateProductModifierByProductID_FullMethodName     = "/menu.product_modifier.ProductModifierService/UpdateProductModifierByProductID"
	ProductModifierService_DeactivateProductModifierByProductID_FullMethodName = "/menu.product_modifier.ProductModifierService/DeactivateProductModifierByProductID"
)

// ProductModifierServiceClient is the client API for ProductModifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductModifierServiceClient interface {
	CreateProductModifier(ctx context.Context, in *CreateProductModifierRequest, opts ...grpc.CallOption) (*CreateProductModifierResponse, error)
	GetProductModifierByProductID(ctx context.Context, in *GetProductModifierByProductIDRequest, opts ...grpc.CallOption) (*GetProductModifierByProductIDResponse, error)
	UpdateProductModifierByProductID(ctx context.Context, in *UpdateProductModifierByProductIDRequest, opts ...grpc.CallOption) (*UpdateProductModifierByProductIDResponse, error)
	DeactivateProductModifierByProductID(ctx context.Context, in *DeactivateProductModifierByProductIDRequest, opts ...grpc.CallOption) (*DeactivateProductModifierByProductIDResponse, error)
}

type productModifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductModifierServiceClient(cc grpc.ClientConnInterface) ProductModifierServiceClient {
	return &productModifierServiceClient{cc}
}

func (c *productModifierServiceClient) CreateProductModifier(ctx context.Context, in *CreateProductModifierRequest, opts ...grpc.CallOption) (*CreateProductModifierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductModifierResponse)
	err := c.cc.Invoke(ctx, ProductModifierService_CreateProductModifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productModifierServiceClient) GetProductModifierByProductID(ctx context.Context, in *GetProductModifierByProductIDRequest, opts ...grpc.CallOption) (*GetProductModifierByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductModifierByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductModifierService_GetProductModifierByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productModifierServiceClient) UpdateProductModifierByProductID(ctx context.Context, in *UpdateProductModifierByProductIDRequest, opts ...grpc.CallOption) (*UpdateProductModifierByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductModifierByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductModifierService_UpdateProductModifierByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productModifierServiceClient) DeactivateProductModifierByProductID(ctx context.Context, in *DeactivateProductModifierByProductIDRequest, opts ...grpc.CallOption) (*DeactivateProductModifierByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateProductModifierByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductModifierService_DeactivateProductModifierByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductModifierServiceServer is the server API for ProductModifierService service.
// All implementations must embed UnimplementedProductModifierServiceServer
// for forward compatibility.
type ProductModifierServiceServer interface {
	CreateProductModifier(context.Context, *CreateProductModifierRequest) (*CreateProductModifierResponse, error)
	GetProductModifierByProductID(context.Context, *GetProductModifierByProductIDRequest) (*GetProductModifierByProductIDResponse, error)
	UpdateProductModifierByProductID(context.Context, *UpdateProductModifierByProductIDRequest) (*UpdateProductModifierByProductIDResponse, error)
	DeactivateProductModifierByProductID(context.Context, *DeactivateProductModifierByProductIDRequest) (*DeactivateProductModifierByProductIDResponse, error)
	mustEmbedUnimplementedProductModifierServiceServer()
}

// UnimplementedProductModifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductModifierServiceServer struct{}

func (UnimplementedProductModifierServiceServer) CreateProductModifier(context.Context, *CreateProductModifierRequest) (*CreateProductModifierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductModifier not implemented")
}
func (UnimplementedProductModifierServiceServer) GetProductModifierByProductID(context.Context, *GetProductModifierByProductIDRequest) (*GetProductModifierByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductModifierByProductID not implemented")
}
func (UnimplementedProductModifierServiceServer) UpdateProductModifierByProductID(context.Context, *UpdateProductModifierByProductIDRequest) (*UpdateProductModifierByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductModifierByProductID not implemented")
}
func (UnimplementedProductModifierServiceServer) DeactivateProductModifierByProductID(context.Context, *DeactivateProductModifierByProductIDRequest) (*DeactivateProductModifierByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateProductModifierByProductID not implemented")
}
func (UnimplementedProductModifierServiceServer) mustEmbedUnimplementedProductModifierServiceServer() {
}
func (UnimplementedProductModifierServiceServer) testEmbeddedByValue() {}

// UnsafeProductModifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductModifierServiceServer will
// result in compilation errors.
type UnsafeProductModifierServiceServer interface {
	mustEmbedUnimplementedProductModifierServiceServer()
}

func RegisterProductModifierServiceServer(s grpc.ServiceRegistrar, srv ProductModifierServiceServer) {
	// If the following call panics, it indicates UnimplementedProductModifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductModifierService_ServiceDesc, srv)
}

func _ProductModifierService_CreateProductModifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductModifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductModifierServiceServer).CreateProductModifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductModifierService_CreateProductModifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductModifierServiceServer).CreateProductModifier(ctx, req.(*CreateProductModifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductModifierService_GetProductModifierByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductModifierByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductModifierServiceServer).GetProductModifierByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductModifierService_GetProductModifierByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductModifierServiceServer).GetProductModifierByProductID(ctx, req.(*GetProductModifierByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductModifierService_UpdateProductModifierByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductModifierByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductModifierServiceServer).UpdateProductModifierByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductModifierService_UpdateProductModifierByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductModifierServiceServer).UpdateProductModifierByProductID(ctx, req.(*UpdateProductModifierByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductModifierService_DeactivateProductModifierByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateProductModifierByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductModifierServiceServer).DeactivateProductModifierByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductModifierService_DeactivateProductModifierByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductModifierServiceServer).DeactivateProductModifierByProductID(ctx, req.(*DeactivateProductModifierByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductModifierService_ServiceDesc is the grpc.ServiceDesc for ProductModifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductModifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menu.product_modifier.ProductModifierService",
	HandlerType: (*ProductModifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductModifier",
			Handler:    _ProductModifierService_CreateProductModifier_Handler,
		},
		{
			MethodName: "GetProductModifierByProductID",
			Handler:    _ProductModifierService_GetProductModifierByProductID_Handler,
		},
		{
			MethodName: "UpdateProductModifierByProductID",
			Handler:    _ProductModifierService_UpdateProductModifierByProductID_Handler,
		},
		{
			MethodName: "DeactivateProductModifierByProductID",
			Handler:    _ProductModifierService_DeactivateProductModifierByProductID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/menu/product_modifier/product_modifier.proto",
}
