// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/product_modifier/product_modifier.proto

package productmodifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductModifierRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinSelection      int32                  `protobuf:"varint,3,opt,name=min_selection,json=minSelection,proto3" json:"min_selection,omitempty"`
	MaxSelection      int32                  `protobuf:"varint,4,opt,name=max_selection,json=maxSelection,proto3" json:"max_selection,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,5,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	IsDefault         bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProductModifierRequest) Reset() {
	*x = CreateProductModifierRequest{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductModifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductModifierRequest) ProtoMessage() {}

func (x *CreateProductModifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductModifierRequest.ProtoReflect.Descriptor instead.
func (*CreateProductModifierRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductModifierRequest) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *CreateProductModifierRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductModifierRequest) GetMinSelection() int32 {
	if x != nil {
		return x.MinSelection
	}
	return 0
}

func (x *CreateProductModifierRequest) GetMaxSelection() int32 {
	if x != nil {
		return x.MaxSelection
	}
	return 0
}

func (x *CreateProductModifierRequest) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *CreateProductModifierRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CreateProductModifierResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProductModifierId uint64                 `protobuf:"varint,2,opt,name=product_modifier_id,json=productModifierId,proto3" json:"product_modifier_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProductModifierResponse) Reset() {
	*x = CreateProductModifierResponse{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductModifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductModifierResponse) ProtoMessage() {}

func (x *CreateProductModifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductModifierResponse.ProtoReflect.Descriptor instead.
func (*CreateProductModifierResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductModifierResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProductModifierResponse) GetProductModifierId() uint64 {
	if x != nil {
		return x.ProductModifierId
	}
	return 0
}

type GetProductModifierByProductIDRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProductModifierByProductIDRequest) Reset() {
	*x = GetProductModifierByProductIDRequest{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductModifierByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductModifierByProductIDRequest) ProtoMessage() {}

func (x *GetProductModifierByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductModifierByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductModifierByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductModifierByProductIDRequest) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

type GetProductModifierByProductIDResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProductModifierId uint64                 `protobuf:"varint,2,opt,name=product_modifier_id,json=productModifierId,proto3" json:"product_modifier_id,omitempty"`
	ModifierProductId uint64                 `protobuf:"varint,3,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinSelection      int32                  `protobuf:"varint,5,opt,name=min_selection,json=minSelection,proto3" json:"min_selection,omitempty"`
	MaxSelection      int32                  `protobuf:"varint,6,opt,name=max_selection,json=maxSelection,proto3" json:"max_selection,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,7,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	IsDefault         bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProductModifierByProductIDResponse) Reset() {
	*x = GetProductModifierByProductIDResponse{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductModifierByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductModifierByProductIDResponse) ProtoMessage() {}

func (x *GetProductModifierByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductModifierByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductModifierByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductModifierByProductIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProductModifierByProductIDResponse) GetProductModifierId() uint64 {
	if x != nil {
		return x.ProductModifierId
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetMinSelection() int32 {
	if x != nil {
		return x.MinSelection
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetMaxSelection() int32 {
	if x != nil {
		return x.MaxSelection
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *GetProductModifierByProductIDResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type UpdateProductModifierByProductIDRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinSelection      int32                  `protobuf:"varint,3,opt,name=min_selection,json=minSelection,proto3" json:"min_selection,omitempty"`
	MaxSelection      int32                  `protobuf:"varint,4,opt,name=max_selection,json=maxSelection,proto3" json:"max_selection,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,5,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	IsDefault         bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateProductModifierByProductIDRequest) Reset() {
	*x = UpdateProductModifierByProductIDRequest{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductModifierByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductModifierByProductIDRequest) ProtoMessage() {}

func (x *UpdateProductModifierByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductModifierByProductIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductModifierByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductModifierByProductIDRequest) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *UpdateProductModifierByProductIDRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateProductModifierByProductIDRequest) GetMinSelection() int32 {
	if x != nil {
		return x.MinSelection
	}
	return 0
}

func (x *UpdateProductModifierByProductIDRequest) GetMaxSelection() int32 {
	if x != nil {
		return x.MaxSelection
	}
	return 0
}

func (x *UpdateProductModifierByProductIDRequest) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *UpdateProductModifierByProductIDRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type UpdateProductModifierByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductModifierByProductIDResponse) Reset() {
	*x = UpdateProductModifierByProductIDResponse{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductModifierByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductModifierByProductIDResponse) ProtoMessage() {}

func (x *UpdateProductModifierByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductModifierByProductIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductModifierByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductModifierByProductIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeactivateProductModifierByProductIDRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeactivateProductModifierByProductIDRequest) Reset() {
	*x = DeactivateProductModifierByProductIDRequest{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductModifierByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductModifierByProductIDRequest) ProtoMessage() {}

func (x *DeactivateProductModifierByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductModifierByProductIDRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductModifierByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateProductModifierByProductIDRequest) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

type DeactivateProductModifierByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductModifierByProductIDResponse) Reset() {
	*x = DeactivateProductModifierByProductIDResponse{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductModifierByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductModifierByProductIDResponse) ProtoMessage() {}

func (x *DeactivateProductModifierByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductModifierByProductIDResponse.ProtoReflect.Descriptor instead.
func (*DeactivateProductModifierByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{7}
}

func (x *DeactivateProductModifierByProductIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_menu_product_modifier_product_modifier_proto protoreflect.FileDescriptor

const file_proto_menu_product_modifier_product_modifier_proto_rawDesc = "" +
	"\n" +
	"2proto/menu/product_modifier/product_modifier.proto\x12\x15menu.product_modifier\"\xfe\x01\n" +
	"\x1cCreateProductModifierRequest\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\rmin_selection\x18\x03 \x01(\x05R\fminSelection\x12#\n" +
	"\rmax_selection\x18\x04 \x01(\x05R\fmaxSelection\x12)\n" +
	"\x10price_adjustment\x18\x05 \x01(\x01R\x0fpriceAdjustment\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\"i\n" +
	"\x1dCreateProductModifierResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13product_modifier_id\x18\x02 \x01(\x04R\x11productModifierId\"V\n" +
	"$GetProductModifierByProductIDRequest\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\"\xd1\x02\n" +
	"%GetProductModifierByProductIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13product_modifier_id\x18\x02 \x01(\x04R\x11productModifierId\x12.\n" +
	"\x13modifier_product_id\x18\x03 \x01(\x04R\x11modifierProductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12#\n" +
	"\rmin_selection\x18\x05 \x01(\x05R\fminSelection\x12#\n" +
	"\rmax_selection\x18\x06 \x01(\x05R\fmaxSelection\x12)\n" +
	"\x10price_adjustment\x18\a \x01(\x01R\x0fpriceAdjustment\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\"\x89\x02\n" +
	"'UpdateProductModifierByProductIDRequest\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\rmin_selection\x18\x03 \x01(\x05R\fminSelection\x12#\n" +
	"\rmax_selection\x18\x04 \x01(\x05R\fmaxSelection\x12)\n" +
	"\x10price_adjustment\x18\x05 \x01(\x01R\x0fpriceAdjustment\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\"D\n" +
	"(UpdateProductModifierByProductIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"+DeactivateProductModifierByProductIDRequest\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\"H\n" +
	",DeactivateProductModifierByProductIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x92\x05\n" +
	"\x16ProductModifierService\x12\x82\x01\n" +
	"\x15CreateProductModifier\x123.menu.product_modifier.CreateProductModifierRequest\x1a4.menu.product_modifier.CreateProductModifierResponse\x12\x9a\x01\n" +
	"\x1dGetProductModifierByProductID\x12;.menu.product_modifier.GetProductModifierByProductIDRequest\x1a<.menu.product_modifier.GetProductModifierByProductIDResponse\x12\xa3\x01\n" +
	" UpdateProductModifierByProductID\x12>.menu.product_modifier.UpdateProductModifierByProductIDRequest\x1a?.menu.product_modifier.UpdateProductModifierByProductIDResponse\x12\xaf\x01\n" +
	"$DeactivateProductModifierByProductID\x12B.menu.product_modifier.DeactivateProductModifierByProductIDRequest\x1aC.menu.product_modifier.DeactivateProductModifierByProductIDResponseBNZLgithub.com/InBitGT/proto-definitions/menu/product_modifier;productmodifierpbb\x06proto3"

var (
	file_proto_menu_product_modifier_product_modifier_proto_rawDescOnce sync.Once
	file_proto_menu_product_modifier_product_modifier_proto_rawDescData []byte
)

func file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP() []byte {
	file_proto_menu_product_modifier_product_modifier_proto_rawDescOnce.Do(func() {
		file_proto_menu_product_modifier_product_modifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_product_modifier_product_modifier_proto_rawDesc), len(file_proto_menu_product_modifier_product_modifier_proto_rawDesc)))
	})
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescData
}

var file_proto_menu_product_modifier_product_modifier_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_menu_product_modifier_product_modifier_proto_goTypes = []any{
	(*CreateProductModifierRequest)(nil),                 // 0: menu.product_modifier.CreateProductModifierRequest
	(*CreateProductModifierResponse)(nil),                // 1: menu.product_modifier.CreateProductModifierResponse
	(*GetProductModifierByProductIDRequest)(nil),         // 2: menu.product_modifier.GetProductModifierByProductIDRequest
	(*GetProductModifierByProductIDResponse)(nil),        // 3: menu.product_modifier.GetProductModifierByProductIDResponse
	(*UpdateProductModifierByProductIDRequest)(nil),      // 4: menu.product_modifier.UpdateProductModifierByProductIDRequest
	(*UpdateProductModifierByProductIDResponse)(nil),     // 5: menu.product_modifier.UpdateProductModifierByProductIDResponse
	(*DeactivateProductModifierByProductIDRequest)(nil),  // 6: menu.product_modifier.DeactivateProductModifierByProductIDRequest
	(*DeactivateProductModifierByProductIDResponse)(nil), // 7: menu.product_modifier.DeactivateProductModifierByProductIDResponse
}
var file_proto_menu_product_modifier_product_modifier_proto_depIdxs = []int32{
	0, // 0: menu.product_modifier.ProductModifierService.CreateProductModifier:input_type -> menu.product_modifier.CreateProductModifierRequest
	2, // 1: menu.product_modifier.ProductModifierService.GetProductModifierByProductID:input_type -> menu.product_modifier.GetProductModifierByProductIDRequest
	4, // 2: menu.product_modifier.ProductModifierService.UpdateProductModifierByProductID:input_type -> menu.product_modifier.UpdateProductModifierByProductIDRequest
	6, // 3: menu.product_modifier.ProductModifierService.DeactivateProductModifierByProductID:input_type -> menu.product_modifier.DeactivateProductModifierByProductIDRequest
	1, // 4: menu.product_modifier.ProductModifierService.CreateProductModifier:output_type -> menu.product_modifier.CreateProductModifierResponse
	3, // 5: menu.product_modifier.ProductModifierService.GetProductModifierByProductID:output_type -> menu.product_modifier.GetProductModifierByProductIDResponse
	5, // 6: menu.product_modifier.ProductModifierService.UpdateProductModifierByProductID:output_type -> menu.product_modifier.UpdateProductModifierByProductIDResponse
	7, // 7: menu.product_modifier.ProductModifierService.DeactivateProductModifierByProductID:output_type -> menu.product_modifier.DeactivateProductModifierByProductIDResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_menu_product_modifier_product_modifier_proto_init() }
func file_proto_menu_product_modifier_product_modifier_proto_init() {
	if File_proto_menu_product_modifier_product_modifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_product_modifier_product_modifier_proto_rawDesc), len(file_proto_menu_product_modifier_product_modifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_product_modifier_product_modifier_proto_goTypes,
		DependencyIndexes: file_proto_menu_product_modifier_product_modifier_proto_depIdxs,
		MessageInfos:      file_proto_menu_product_modifier_product_modifier_proto_msgTypes,
	}.Build()
	File_proto_menu_product_modifier_product_modifier_proto = out.File
	file_proto_menu_product_modifier_product_modifier_proto_goTypes = nil
	file_proto_menu_product_modifier_product_modifier_proto_depIdxs = nil
}
