// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/product_modifier/product_modifier.proto

package productmodifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductModifierRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierProductId uint64                 `protobuf:"varint,1,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinSelection      int32                  `protobuf:"varint,3,opt,name=min_selection,json=minSelection,proto3" json:"min_selection,omitempty"`
	MaxSelection      int32                  `protobuf:"varint,4,opt,name=max_selection,json=maxSelection,proto3" json:"max_selection,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,5,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	IsDefault         bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProductModifierRequest) Reset() {
	*x = CreateProductModifierRequest{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductModifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductModifierRequest) ProtoMessage() {}

func (x *CreateProductModifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductModifierRequest.ProtoReflect.Descriptor instead.
func (*CreateProductModifierRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductModifierRequest) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *CreateProductModifierRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductModifierRequest) GetMinSelection() int32 {
	if x != nil {
		return x.MinSelection
	}
	return 0
}

func (x *CreateProductModifierRequest) GetMaxSelection() int32 {
	if x != nil {
		return x.MaxSelection
	}
	return 0
}

func (x *CreateProductModifierRequest) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *CreateProductModifierRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CreateProductModifierResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProductModifierId uint64                 `protobuf:"varint,2,opt,name=product_modifier_id,json=productModifierId,proto3" json:"product_modifier_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProductModifierResponse) Reset() {
	*x = CreateProductModifierResponse{}
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductModifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductModifierResponse) ProtoMessage() {}

func (x *CreateProductModifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_modifier_product_modifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductModifierResponse.ProtoReflect.Descriptor instead.
func (*CreateProductModifierResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductModifierResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProductModifierResponse) GetProductModifierId() uint64 {
	if x != nil {
		return x.ProductModifierId
	}
	return 0
}

var File_proto_menu_product_modifier_product_modifier_proto protoreflect.FileDescriptor

const file_proto_menu_product_modifier_product_modifier_proto_rawDesc = "" +
	"\n" +
	"2proto/menu/product_modifier/product_modifier.proto\x12\x15menu.product_modifier\"\xfe\x01\n" +
	"\x1cCreateProductModifierRequest\x12.\n" +
	"\x13modifier_product_id\x18\x01 \x01(\x04R\x11modifierProductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\rmin_selection\x18\x03 \x01(\x05R\fminSelection\x12#\n" +
	"\rmax_selection\x18\x04 \x01(\x05R\fmaxSelection\x12)\n" +
	"\x10price_adjustment\x18\x05 \x01(\x01R\x0fpriceAdjustment\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\"i\n" +
	"\x1dCreateProductModifierResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13product_modifier_id\x18\x02 \x01(\x04R\x11productModifierId2\x9d\x01\n" +
	"\x16ProductModifierService\x12\x82\x01\n" +
	"\x15CreateProductModifier\x123.menu.product_modifier.CreateProductModifierRequest\x1a4.menu.product_modifier.CreateProductModifierResponseBNZLgithub.com/InBitGT/proto-definitions/menu/product_modifier;productmodifierpbb\x06proto3"

var (
	file_proto_menu_product_modifier_product_modifier_proto_rawDescOnce sync.Once
	file_proto_menu_product_modifier_product_modifier_proto_rawDescData []byte
)

func file_proto_menu_product_modifier_product_modifier_proto_rawDescGZIP() []byte {
	file_proto_menu_product_modifier_product_modifier_proto_rawDescOnce.Do(func() {
		file_proto_menu_product_modifier_product_modifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_product_modifier_product_modifier_proto_rawDesc), len(file_proto_menu_product_modifier_product_modifier_proto_rawDesc)))
	})
	return file_proto_menu_product_modifier_product_modifier_proto_rawDescData
}

var file_proto_menu_product_modifier_product_modifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_menu_product_modifier_product_modifier_proto_goTypes = []any{
	(*CreateProductModifierRequest)(nil),  // 0: menu.product_modifier.CreateProductModifierRequest
	(*CreateProductModifierResponse)(nil), // 1: menu.product_modifier.CreateProductModifierResponse
}
var file_proto_menu_product_modifier_product_modifier_proto_depIdxs = []int32{
	0, // 0: menu.product_modifier.ProductModifierService.CreateProductModifier:input_type -> menu.product_modifier.CreateProductModifierRequest
	1, // 1: menu.product_modifier.ProductModifierService.CreateProductModifier:output_type -> menu.product_modifier.CreateProductModifierResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_menu_product_modifier_product_modifier_proto_init() }
func file_proto_menu_product_modifier_product_modifier_proto_init() {
	if File_proto_menu_product_modifier_product_modifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_product_modifier_product_modifier_proto_rawDesc), len(file_proto_menu_product_modifier_product_modifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_product_modifier_product_modifier_proto_goTypes,
		DependencyIndexes: file_proto_menu_product_modifier_product_modifier_proto_depIdxs,
		MessageInfos:      file_proto_menu_product_modifier_product_modifier_proto_msgTypes,
	}.Build()
	File_proto_menu_product_modifier_product_modifier_proto = out.File
	file_proto_menu_product_modifier_product_modifier_proto_goTypes = nil
	file_proto_menu_product_modifier_product_modifier_proto_depIdxs = nil
}
