// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/menu/product_options/product_options.proto

package productoptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 0 = crear; con valor = actualizar esa variante
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceAdjustment float64                `protobuf:"fixed64,3,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,4,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VariantInput) Reset() {
	*x = VariantInput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantInput) ProtoMessage() {}

func (x *VariantInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantInput.ProtoReflect.Descriptor instead.
func (*VariantInput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{0}
}

func (x *VariantInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VariantInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariantInput) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *VariantInput) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

type IngredientInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngredientId  uint64                 `protobuf:"varint,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	WasteFactor   float64                `protobuf:"fixed64,4,opt,name=waste_factor,json=wasteFactor,proto3" json:"waste_factor,omitempty"`
	VariantId     uint64                 `protobuf:"varint,5,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`      // amarre por ID (variante existente)
	VariantName   string                 `protobuf:"bytes,6,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"` // amarre por nombre (variante del mismo request)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientInput) Reset() {
	*x = IngredientInput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientInput) ProtoMessage() {}

func (x *IngredientInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientInput.ProtoReflect.Descriptor instead.
func (*IngredientInput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{1}
}

func (x *IngredientInput) GetIngredientId() uint64 {
	if x != nil {
		return x.IngredientId
	}
	return 0
}

func (x *IngredientInput) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *IngredientInput) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *IngredientInput) GetWasteFactor() float64 {
	if x != nil {
		return x.WasteFactor
	}
	return 0
}

func (x *IngredientInput) GetVariantId() uint64 {
	if x != nil {
		return x.VariantId
	}
	return 0
}

func (x *IngredientInput) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

type RecipeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ingredients   []*IngredientInput     `protobuf:"bytes,3,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeInput) Reset() {
	*x = RecipeInput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeInput) ProtoMessage() {}

func (x *RecipeInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeInput.ProtoReflect.Descriptor instead.
func (*RecipeInput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{2}
}

func (x *RecipeInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeInput) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecipeInput) GetIngredients() []*IngredientInput {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

// Los flags set_* indican si la sección viene en el request.
// set_x = false → no se toca. set_x = true con lista vacía → se elimina.
type SetProductOptionsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName        string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // para el nombre por defecto de la receta
	SetVariants        bool                   `protobuf:"varint,3,opt,name=set_variants,json=setVariants,proto3" json:"set_variants,omitempty"`
	Variants           []*VariantInput        `protobuf:"bytes,4,rep,name=variants,proto3" json:"variants,omitempty"`
	SetModifiers       bool                   `protobuf:"varint,5,opt,name=set_modifiers,json=setModifiers,proto3" json:"set_modifiers,omitempty"`
	ProductModifierIds []uint64               `protobuf:"varint,6,rep,packed,name=product_modifier_ids,json=productModifierIds,proto3" json:"product_modifier_ids,omitempty"`
	SetRecipe          bool                   `protobuf:"varint,7,opt,name=set_recipe,json=setRecipe,proto3" json:"set_recipe,omitempty"`
	Recipe             *RecipeInput           `protobuf:"bytes,8,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetProductOptionsRequest) Reset() {
	*x = SetProductOptionsRequest{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProductOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProductOptionsRequest) ProtoMessage() {}

func (x *SetProductOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProductOptionsRequest.ProtoReflect.Descriptor instead.
func (*SetProductOptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{3}
}

func (x *SetProductOptionsRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetProductOptionsRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SetProductOptionsRequest) GetSetVariants() bool {
	if x != nil {
		return x.SetVariants
	}
	return false
}

func (x *SetProductOptionsRequest) GetVariants() []*VariantInput {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *SetProductOptionsRequest) GetSetModifiers() bool {
	if x != nil {
		return x.SetModifiers
	}
	return false
}

func (x *SetProductOptionsRequest) GetProductModifierIds() []uint64 {
	if x != nil {
		return x.ProductModifierIds
	}
	return nil
}

func (x *SetProductOptionsRequest) GetSetRecipe() bool {
	if x != nil {
		return x.SetRecipe
	}
	return false
}

func (x *SetProductOptionsRequest) GetRecipe() *RecipeInput {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type VariantOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceAdjustment float64                `protobuf:"fixed64,3,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,4,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VariantOutput) Reset() {
	*x = VariantOutput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantOutput) ProtoMessage() {}

func (x *VariantOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantOutput.ProtoReflect.Descriptor instead.
func (*VariantOutput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{4}
}

func (x *VariantOutput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VariantOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariantOutput) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *VariantOutput) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

type SetProductOptionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Variants         []*VariantOutput       `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	RecipeId         uint64                 `protobuf:"varint,4,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	IngredientsCount int32                  `protobuf:"varint,5,opt,name=ingredients_count,json=ingredientsCount,proto3" json:"ingredients_count,omitempty"`
	ModifiersCount   int32                  `protobuf:"varint,6,opt,name=modifiers_count,json=modifiersCount,proto3" json:"modifiers_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetProductOptionsResponse) Reset() {
	*x = SetProductOptionsResponse{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProductOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProductOptionsResponse) ProtoMessage() {}

func (x *SetProductOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProductOptionsResponse.ProtoReflect.Descriptor instead.
func (*SetProductOptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{5}
}

func (x *SetProductOptionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetProductOptionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SetProductOptionsResponse) GetVariants() []*VariantOutput {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *SetProductOptionsResponse) GetRecipeId() uint64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

func (x *SetProductOptionsResponse) GetIngredientsCount() int32 {
	if x != nil {
		return x.IngredientsCount
	}
	return 0
}

func (x *SetProductOptionsResponse) GetModifiersCount() int32 {
	if x != nil {
		return x.ModifiersCount
	}
	return 0
}

type GetProductOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOptionsRequest) Reset() {
	*x = GetProductOptionsRequest{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOptionsRequest) ProtoMessage() {}

func (x *GetProductOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetProductOptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductOptionsRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type IngredientOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IngredientId  uint64                 `protobuf:"varint,2,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	WasteFactor   float64                `protobuf:"fixed64,5,opt,name=waste_factor,json=wasteFactor,proto3" json:"waste_factor,omitempty"`
	VariantId     uint64                 `protobuf:"varint,6,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"` // 0 = se consume siempre
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientOutput) Reset() {
	*x = IngredientOutput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientOutput) ProtoMessage() {}

func (x *IngredientOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientOutput.ProtoReflect.Descriptor instead.
func (*IngredientOutput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{7}
}

func (x *IngredientOutput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngredientOutput) GetIngredientId() uint64 {
	if x != nil {
		return x.IngredientId
	}
	return 0
}

func (x *IngredientOutput) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *IngredientOutput) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *IngredientOutput) GetWasteFactor() float64 {
	if x != nil {
		return x.WasteFactor
	}
	return 0
}

func (x *IngredientOutput) GetVariantId() uint64 {
	if x != nil {
		return x.VariantId
	}
	return 0
}

type RecipeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Ingredients   []*IngredientOutput    `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeOutput) Reset() {
	*x = RecipeOutput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeOutput) ProtoMessage() {}

func (x *RecipeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeOutput.ProtoReflect.Descriptor instead.
func (*RecipeOutput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{8}
}

func (x *RecipeOutput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecipeOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeOutput) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecipeOutput) GetIngredients() []*IngredientOutput {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type ModifierOutput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductModifierId uint64                 `protobuf:"varint,1,opt,name=product_modifier_id,json=productModifierId,proto3" json:"product_modifier_id,omitempty"`
	ModifierProductId uint64                 `protobuf:"varint,2,opt,name=modifier_product_id,json=modifierProductId,proto3" json:"modifier_product_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinSelection      int32                  `protobuf:"varint,4,opt,name=min_selection,json=minSelection,proto3" json:"min_selection,omitempty"`
	MaxSelection      int32                  `protobuf:"varint,5,opt,name=max_selection,json=maxSelection,proto3" json:"max_selection,omitempty"`
	PriceAdjustment   float64                `protobuf:"fixed64,6,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	IsDefault         bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	ModifierType      string                 `protobuf:"bytes,8,opt,name=modifier_type,json=modifierType,proto3" json:"modifier_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifierOutput) Reset() {
	*x = ModifierOutput{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifierOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifierOutput) ProtoMessage() {}

func (x *ModifierOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifierOutput.ProtoReflect.Descriptor instead.
func (*ModifierOutput) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{9}
}

func (x *ModifierOutput) GetProductModifierId() uint64 {
	if x != nil {
		return x.ProductModifierId
	}
	return 0
}

func (x *ModifierOutput) GetModifierProductId() uint64 {
	if x != nil {
		return x.ModifierProductId
	}
	return 0
}

func (x *ModifierOutput) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ModifierOutput) GetMinSelection() int32 {
	if x != nil {
		return x.MinSelection
	}
	return 0
}

func (x *ModifierOutput) GetMaxSelection() int32 {
	if x != nil {
		return x.MaxSelection
	}
	return 0
}

func (x *ModifierOutput) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *ModifierOutput) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ModifierOutput) GetModifierType() string {
	if x != nil {
		return x.ModifierType
	}
	return ""
}

type GetProductOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Variants      []*VariantOutput       `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	Recipe        *RecipeOutput          `protobuf:"bytes,3,opt,name=recipe,proto3" json:"recipe,omitempty"` // null si no tiene receta
	Modifiers     []*ModifierOutput      `protobuf:"bytes,4,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOptionsResponse) Reset() {
	*x = GetProductOptionsResponse{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOptionsResponse) ProtoMessage() {}

func (x *GetProductOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetProductOptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductOptionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProductOptionsResponse) GetVariants() []*VariantOutput {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *GetProductOptionsResponse) GetRecipe() *RecipeOutput {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *GetProductOptionsResponse) GetModifiers() []*ModifierOutput {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type GetProductOptionsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []uint64               `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOptionsBatchRequest) Reset() {
	*x = GetProductOptionsBatchRequest{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOptionsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOptionsBatchRequest) ProtoMessage() {}

func (x *GetProductOptionsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOptionsBatchRequest.ProtoReflect.Descriptor instead.
func (*GetProductOptionsBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductOptionsBatchRequest) GetProductIds() []uint64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ProductOptionsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Variants      []*VariantOutput       `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	Recipe        *RecipeOutput          `protobuf:"bytes,3,opt,name=recipe,proto3" json:"recipe,omitempty"`                              // null si no tiene receta
	Modifiers     []*ModifierOutput      `protobuf:"bytes,4,rep,name=modifiers,proto3" json:"modifiers,omitempty"`                        // modificadores ASIGNADOS al producto
	OwnModifier   *ModifierOutput        `protobuf:"bytes,5,opt,name=own_modifier,json=ownModifier,proto3" json:"own_modifier,omitempty"` // configuración propia, si el producto ES un modificador
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductOptionsEntry) Reset() {
	*x = ProductOptionsEntry{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOptionsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOptionsEntry) ProtoMessage() {}

func (x *ProductOptionsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOptionsEntry.ProtoReflect.Descriptor instead.
func (*ProductOptionsEntry) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{12}
}

func (x *ProductOptionsEntry) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductOptionsEntry) GetVariants() []*VariantOutput {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProductOptionsEntry) GetRecipe() *RecipeOutput {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *ProductOptionsEntry) GetModifiers() []*ModifierOutput {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *ProductOptionsEntry) GetOwnModifier() *ModifierOutput {
	if x != nil {
		return x.OwnModifier
	}
	return nil
}

type GetProductOptionsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Entries       []*ProductOptionsEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOptionsBatchResponse) Reset() {
	*x = GetProductOptionsBatchResponse{}
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOptionsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOptionsBatchResponse) ProtoMessage() {}

func (x *GetProductOptionsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_product_options_product_options_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOptionsBatchResponse.ProtoReflect.Descriptor instead.
func (*GetProductOptionsBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_product_options_product_options_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductOptionsBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProductOptionsBatchResponse) GetEntries() []*ProductOptionsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_menu_product_options_product_options_proto protoreflect.FileDescriptor

const file_proto_menu_product_options_product_options_proto_rawDesc = "" +
	"\n" +
	"0proto/menu/product_options/product_options.proto\x12\x14menu.product_options\"\x86\x01\n" +
	"\fVariantInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10price_adjustment\x18\x03 \x01(\x01R\x0fpriceAdjustment\x12'\n" +
	"\x0fadjustment_type\x18\x04 \x01(\tR\x0eadjustmentType\"\xcb\x01\n" +
	"\x0fIngredientInput\x12#\n" +
	"\ringredient_id\x18\x01 \x01(\x04R\fingredientId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12!\n" +
	"\fwaste_factor\x18\x04 \x01(\x01R\vwasteFactor\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x05 \x01(\x04R\tvariantId\x12!\n" +
	"\fvariant_name\x18\x06 \x01(\tR\vvariantName\"\x84\x01\n" +
	"\vRecipeInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12G\n" +
	"\vingredients\x18\x03 \x03(\v2%.menu.product_options.IngredientInputR\vingredients\"\xf0\x02\n" +
	"\x18SetProductOptionsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12!\n" +
	"\fset_variants\x18\x03 \x01(\bR\vsetVariants\x12>\n" +
	"\bvariants\x18\x04 \x03(\v2\".menu.product_options.VariantInputR\bvariants\x12#\n" +
	"\rset_modifiers\x18\x05 \x01(\bR\fsetModifiers\x120\n" +
	"\x14product_modifier_ids\x18\x06 \x03(\x04R\x12productModifierIds\x12\x1d\n" +
	"\n" +
	"set_recipe\x18\a \x01(\bR\tsetRecipe\x129\n" +
	"\x06recipe\x18\b \x01(\v2!.menu.product_options.RecipeInputR\x06recipe\"\x87\x01\n" +
	"\rVariantOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10price_adjustment\x18\x03 \x01(\x01R\x0fpriceAdjustment\x12'\n" +
	"\x0fadjustment_type\x18\x04 \x01(\tR\x0eadjustmentType\"\x8e\x02\n" +
	"\x19SetProductOptionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12?\n" +
	"\bvariants\x18\x03 \x03(\v2#.menu.product_options.VariantOutputR\bvariants\x12\x1b\n" +
	"\trecipe_id\x18\x04 \x01(\x04R\brecipeId\x12+\n" +
	"\x11ingredients_count\x18\x05 \x01(\x05R\x10ingredientsCount\x12'\n" +
	"\x0fmodifiers_count\x18\x06 \x01(\x05R\x0emodifiersCount\"9\n" +
	"\x18GetProductOptionsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\xb9\x01\n" +
	"\x10IngredientOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\ringredient_id\x18\x02 \x01(\x04R\fingredientId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12!\n" +
	"\fwaste_factor\x18\x05 \x01(\x01R\vwasteFactor\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x06 \x01(\x04R\tvariantId\"\x96\x01\n" +
	"\fRecipeOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12H\n" +
	"\vingredients\x18\x04 \x03(\v2&.menu.product_options.IngredientOutputR\vingredients\"\xc5\x02\n" +
	"\x0eModifierOutput\x12.\n" +
	"\x13product_modifier_id\x18\x01 \x01(\x04R\x11productModifierId\x12.\n" +
	"\x13modifier_product_id\x18\x02 \x01(\x04R\x11modifierProductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12#\n" +
	"\rmin_selection\x18\x04 \x01(\x05R\fminSelection\x12#\n" +
	"\rmax_selection\x18\x05 \x01(\x05R\fmaxSelection\x12)\n" +
	"\x10price_adjustment\x18\x06 \x01(\x01R\x0fpriceAdjustment\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12#\n" +
	"\rmodifier_type\x18\b \x01(\tR\fmodifierType\"\xf6\x01\n" +
	"\x19GetProductOptionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\bvariants\x18\x02 \x03(\v2#.menu.product_options.VariantOutputR\bvariants\x12:\n" +
	"\x06recipe\x18\x03 \x01(\v2\".menu.product_options.RecipeOutputR\x06recipe\x12B\n" +
	"\tmodifiers\x18\x04 \x03(\v2$.menu.product_options.ModifierOutputR\tmodifiers\"@\n" +
	"\x1dGetProductOptionsBatchRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x04R\n" +
	"productIds\"\xbe\x02\n" +
	"\x13ProductOptionsEntry\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12?\n" +
	"\bvariants\x18\x02 \x03(\v2#.menu.product_options.VariantOutputR\bvariants\x12:\n" +
	"\x06recipe\x18\x03 \x01(\v2\".menu.product_options.RecipeOutputR\x06recipe\x12B\n" +
	"\tmodifiers\x18\x04 \x03(\v2$.menu.product_options.ModifierOutputR\tmodifiers\x12G\n" +
	"\fown_modifier\x18\x05 \x01(\v2$.menu.product_options.ModifierOutputR\vownModifier\"\x7f\n" +
	"\x1eGetProductOptionsBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12C\n" +
	"\aentries\x18\x02 \x03(\v2).menu.product_options.ProductOptionsEntryR\aentries2\x89\x03\n" +
	"\x15ProductOptionsService\x12t\n" +
	"\x11SetProductOptions\x12..menu.product_options.SetProductOptionsRequest\x1a/.menu.product_options.SetProductOptionsResponse\x12t\n" +
	"\x11GetProductOptions\x12..menu.product_options.GetProductOptionsRequest\x1a/.menu.product_options.GetProductOptionsResponse\x12\x83\x01\n" +
	"\x16GetProductOptionsBatch\x123.menu.product_options.GetProductOptionsBatchRequest\x1a4.menu.product_options.GetProductOptionsBatchResponseBLZJgithub.com/InBitGT/proto-definitions/menu/product_options;productoptionspbb\x06proto3"

var (
	file_proto_menu_product_options_product_options_proto_rawDescOnce sync.Once
	file_proto_menu_product_options_product_options_proto_rawDescData []byte
)

func file_proto_menu_product_options_product_options_proto_rawDescGZIP() []byte {
	file_proto_menu_product_options_product_options_proto_rawDescOnce.Do(func() {
		file_proto_menu_product_options_product_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_product_options_product_options_proto_rawDesc), len(file_proto_menu_product_options_product_options_proto_rawDesc)))
	})
	return file_proto_menu_product_options_product_options_proto_rawDescData
}

var file_proto_menu_product_options_product_options_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_menu_product_options_product_options_proto_goTypes = []any{
	(*VariantInput)(nil),                   // 0: menu.product_options.VariantInput
	(*IngredientInput)(nil),                // 1: menu.product_options.IngredientInput
	(*RecipeInput)(nil),                    // 2: menu.product_options.RecipeInput
	(*SetProductOptionsRequest)(nil),       // 3: menu.product_options.SetProductOptionsRequest
	(*VariantOutput)(nil),                  // 4: menu.product_options.VariantOutput
	(*SetProductOptionsResponse)(nil),      // 5: menu.product_options.SetProductOptionsResponse
	(*GetProductOptionsRequest)(nil),       // 6: menu.product_options.GetProductOptionsRequest
	(*IngredientOutput)(nil),               // 7: menu.product_options.IngredientOutput
	(*RecipeOutput)(nil),                   // 8: menu.product_options.RecipeOutput
	(*ModifierOutput)(nil),                 // 9: menu.product_options.ModifierOutput
	(*GetProductOptionsResponse)(nil),      // 10: menu.product_options.GetProductOptionsResponse
	(*GetProductOptionsBatchRequest)(nil),  // 11: menu.product_options.GetProductOptionsBatchRequest
	(*ProductOptionsEntry)(nil),            // 12: menu.product_options.ProductOptionsEntry
	(*GetProductOptionsBatchResponse)(nil), // 13: menu.product_options.GetProductOptionsBatchResponse
}
var file_proto_menu_product_options_product_options_proto_depIdxs = []int32{
	1,  // 0: menu.product_options.RecipeInput.ingredients:type_name -> menu.product_options.IngredientInput
	0,  // 1: menu.product_options.SetProductOptionsRequest.variants:type_name -> menu.product_options.VariantInput
	2,  // 2: menu.product_options.SetProductOptionsRequest.recipe:type_name -> menu.product_options.RecipeInput
	4,  // 3: menu.product_options.SetProductOptionsResponse.variants:type_name -> menu.product_options.VariantOutput
	7,  // 4: menu.product_options.RecipeOutput.ingredients:type_name -> menu.product_options.IngredientOutput
	4,  // 5: menu.product_options.GetProductOptionsResponse.variants:type_name -> menu.product_options.VariantOutput
	8,  // 6: menu.product_options.GetProductOptionsResponse.recipe:type_name -> menu.product_options.RecipeOutput
	9,  // 7: menu.product_options.GetProductOptionsResponse.modifiers:type_name -> menu.product_options.ModifierOutput
	4,  // 8: menu.product_options.ProductOptionsEntry.variants:type_name -> menu.product_options.VariantOutput
	8,  // 9: menu.product_options.ProductOptionsEntry.recipe:type_name -> menu.product_options.RecipeOutput
	9,  // 10: menu.product_options.ProductOptionsEntry.modifiers:type_name -> menu.product_options.ModifierOutput
	9,  // 11: menu.product_options.ProductOptionsEntry.own_modifier:type_name -> menu.product_options.ModifierOutput
	12, // 12: menu.product_options.GetProductOptionsBatchResponse.entries:type_name -> menu.product_options.ProductOptionsEntry
	3,  // 13: menu.product_options.ProductOptionsService.SetProductOptions:input_type -> menu.product_options.SetProductOptionsRequest
	6,  // 14: menu.product_options.ProductOptionsService.GetProductOptions:input_type -> menu.product_options.GetProductOptionsRequest
	11, // 15: menu.product_options.ProductOptionsService.GetProductOptionsBatch:input_type -> menu.product_options.GetProductOptionsBatchRequest
	5,  // 16: menu.product_options.ProductOptionsService.SetProductOptions:output_type -> menu.product_options.SetProductOptionsResponse
	10, // 17: menu.product_options.ProductOptionsService.GetProductOptions:output_type -> menu.product_options.GetProductOptionsResponse
	13, // 18: menu.product_options.ProductOptionsService.GetProductOptionsBatch:output_type -> menu.product_options.GetProductOptionsBatchResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_menu_product_options_product_options_proto_init() }
func file_proto_menu_product_options_product_options_proto_init() {
	if File_proto_menu_product_options_product_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_product_options_product_options_proto_rawDesc), len(file_proto_menu_product_options_product_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_product_options_product_options_proto_goTypes,
		DependencyIndexes: file_proto_menu_product_options_product_options_proto_depIdxs,
		MessageInfos:      file_proto_menu_product_options_product_options_proto_msgTypes,
	}.Build()
	File_proto_menu_product_options_product_options_proto = out.File
	file_proto_menu_product_options_product_options_proto_goTypes = nil
	file_proto_menu_product_options_product_options_proto_depIdxs = nil
}
