// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/menu/product_options/product_options.proto

package productoptionspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductOptionsService_SetProductOptions_FullMethodName = "/menu.product_options.ProductOptionsService/SetProductOptions"
	ProductOptionsService_GetProductOptions_FullMethodName = "/menu.product_options.ProductOptionsService/GetProductOptions"
)

// ProductOptionsServiceClient is the client API for ProductOptionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Variantes, receta y modificadores asignados de un producto, en una sola
// transacción de menu-service. Lo usa inventory-service desde /product/full.
type ProductOptionsServiceClient interface {
	SetProductOptions(ctx context.Context, in *SetProductOptionsRequest, opts ...grpc.CallOption) (*SetProductOptionsResponse, error)
	GetProductOptions(ctx context.Context, in *GetProductOptionsRequest, opts ...grpc.CallOption) (*GetProductOptionsResponse, error)
}

type productOptionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductOptionsServiceClient(cc grpc.ClientConnInterface) ProductOptionsServiceClient {
	return &productOptionsServiceClient{cc}
}

func (c *productOptionsServiceClient) SetProductOptions(ctx context.Context, in *SetProductOptionsRequest, opts ...grpc.CallOption) (*SetProductOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProductOptionsResponse)
	err := c.cc.Invoke(ctx, ProductOptionsService_SetProductOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productOptionsServiceClient) GetProductOptions(ctx context.Context, in *GetProductOptionsRequest, opts ...grpc.CallOption) (*GetProductOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductOptionsResponse)
	err := c.cc.Invoke(ctx, ProductOptionsService_GetProductOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductOptionsServiceServer is the server API for ProductOptionsService service.
// All implementations must embed UnimplementedProductOptionsServiceServer
// for forward compatibility.
//
// Variantes, receta y modificadores asignados de un producto, en una sola
// transacción de menu-service. Lo usa inventory-service desde /product/full.
type ProductOptionsServiceServer interface {
	SetProductOptions(context.Context, *SetProductOptionsRequest) (*SetProductOptionsResponse, error)
	GetProductOptions(context.Context, *GetProductOptionsRequest) (*GetProductOptionsResponse, error)
	mustEmbedUnimplementedProductOptionsServiceServer()
}

// UnimplementedProductOptionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductOptionsServiceServer struct{}

func (UnimplementedProductOptionsServiceServer) SetProductOptions(context.Context, *SetProductOptionsRequest) (*SetProductOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProductOptions not implemented")
}
func (UnimplementedProductOptionsServiceServer) GetProductOptions(context.Context, *GetProductOptionsRequest) (*GetProductOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductOptions not implemented")
}
func (UnimplementedProductOptionsServiceServer) mustEmbedUnimplementedProductOptionsServiceServer() {}
func (UnimplementedProductOptionsServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductOptionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductOptionsServiceServer will
// result in compilation errors.
type UnsafeProductOptionsServiceServer interface {
	mustEmbedUnimplementedProductOptionsServiceServer()
}

func RegisterProductOptionsServiceServer(s grpc.ServiceRegistrar, srv ProductOptionsServiceServer) {
	// If the following call panics, it indicates UnimplementedProductOptionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductOptionsService_ServiceDesc, srv)
}

func _ProductOptionsService_SetProductOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProductOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductOptionsServiceServer).SetProductOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductOptionsService_SetProductOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductOptionsServiceServer).SetProductOptions(ctx, req.(*SetProductOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductOptionsService_GetProductOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductOptionsServiceServer).GetProductOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductOptionsService_GetProductOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductOptionsServiceServer).GetProductOptions(ctx, req.(*GetProductOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductOptionsService_ServiceDesc is the grpc.ServiceDesc for ProductOptionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductOptionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menu.product_options.ProductOptionsService",
	HandlerType: (*ProductOptionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetProductOptions",
			Handler:    _ProductOptionsService_SetProductOptions_Handler,
		},
		{
			MethodName: "GetProductOptions",
			Handler:    _ProductOptionsService_GetProductOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/menu/product_options/product_options.proto",
}
