// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/customer/customer_credit/customer_credit.proto

package customercreditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerCreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint64                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerCreditRequest) Reset() {
	*x = GetCustomerCreditRequest{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerCreditRequest) ProtoMessage() {}

func (x *GetCustomerCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerCreditRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerCreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerCreditRequest) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetCustomerCreditResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CustomerId      uint64                 `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	HasCredit       bool                   `protobuf:"varint,3,opt,name=has_credit,json=hasCredit,proto3" json:"has_credit,omitempty"`
	CreditLimit     float64                `protobuf:"fixed64,4,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	CreditAvailable float64                `protobuf:"fixed64,5,opt,name=credit_available,json=creditAvailable,proto3" json:"credit_available,omitempty"`
	IsOverdue       bool                   `protobuf:"varint,6,opt,name=is_overdue,json=isOverdue,proto3" json:"is_overdue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCustomerCreditResponse) Reset() {
	*x = GetCustomerCreditResponse{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerCreditResponse) ProtoMessage() {}

func (x *GetCustomerCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerCreditResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerCreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerCreditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCustomerCreditResponse) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *GetCustomerCreditResponse) GetHasCredit() bool {
	if x != nil {
		return x.HasCredit
	}
	return false
}

func (x *GetCustomerCreditResponse) GetCreditLimit() float64 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

func (x *GetCustomerCreditResponse) GetCreditAvailable() float64 {
	if x != nil {
		return x.CreditAvailable
	}
	return 0
}

func (x *GetCustomerCreditResponse) GetIsOverdue() bool {
	if x != nil {
		return x.IsOverdue
	}
	return false
}

type ChargeCreditRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           uint64                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId              uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AllowOverride        bool                   `protobuf:"varint,6,opt,name=allow_override,json=allowOverride,proto3" json:"allow_override,omitempty"`
	OverrideAuthorizedBy uint64                 `protobuf:"varint,7,opt,name=override_authorized_by,json=overrideAuthorizedBy,proto3" json:"override_authorized_by,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChargeCreditRequest) Reset() {
	*x = ChargeCreditRequest{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeCreditRequest) ProtoMessage() {}

func (x *ChargeCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeCreditRequest.ProtoReflect.Descriptor instead.
func (*ChargeCreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{2}
}

func (x *ChargeCreditRequest) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *ChargeCreditRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChargeCreditRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ChargeCreditRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChargeCreditRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChargeCreditRequest) GetAllowOverride() bool {
	if x != nil {
		return x.AllowOverride
	}
	return false
}

func (x *ChargeCreditRequest) GetOverrideAuthorizedBy() uint64 {
	if x != nil {
		return x.OverrideAuthorizedBy
	}
	return 0
}

type ChargeCreditResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CreditAvailable float64                `protobuf:"fixed64,2,opt,name=credit_available,json=creditAvailable,proto3" json:"credit_available,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChargeCreditResponse) Reset() {
	*x = ChargeCreditResponse{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeCreditResponse) ProtoMessage() {}

func (x *ChargeCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeCreditResponse.ProtoReflect.Descriptor instead.
func (*ChargeCreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{3}
}

func (x *ChargeCreditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChargeCreditResponse) GetCreditAvailable() float64 {
	if x != nil {
		return x.CreditAvailable
	}
	return 0
}

func (x *ChargeCreditResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReleaseCreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint64                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCreditRequest) Reset() {
	*x = ReleaseCreditRequest{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditRequest) ProtoMessage() {}

func (x *ReleaseCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseCreditRequest) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *ReleaseCreditRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReleaseCreditRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReleaseCreditRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReleaseCreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCreditResponse) Reset() {
	*x = ReleaseCreditResponse{}
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditResponse) ProtoMessage() {}

func (x *ReleaseCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_credit_customer_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseCreditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_customer_customer_credit_customer_credit_proto protoreflect.FileDescriptor

const file_proto_customer_customer_credit_customer_credit_proto_rawDesc = "" +
	"\n" +
	"4proto/customer/customer_credit/customer_credit.proto\x12\x0fcustomer.credit\";\n" +
	"\x18GetCustomerCreditRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x04R\n" +
	"customerId\"\xe2\x01\n" +
	"\x19GetCustomerCreditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x04R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"has_credit\x18\x03 \x01(\bR\thasCredit\x12!\n" +
	"\fcredit_limit\x18\x04 \x01(\x01R\vcreditLimit\x12)\n" +
	"\x10credit_available\x18\x05 \x01(\x01R\x0fcreditAvailable\x12\x1d\n" +
	"\n" +
	"is_overdue\x18\x06 \x01(\bR\tisOverdue\"\x81\x02\n" +
	"\x13ChargeCreditRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x04R\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\x0eallow_override\x18\x06 \x01(\bR\rallowOverride\x124\n" +
	"\x16override_authorized_by\x18\a \x01(\x04R\x14overrideAuthorizedBy\"\x80\x01\n" +
	"\x14ChargeCreditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10credit_available\x18\x02 \x01(\x01R\x0fcreditAvailable\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x83\x01\n" +
	"\x14ReleaseCreditRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x04R\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\"1\n" +
	"\x15ReleaseCreditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc0\x02\n" +
	"\x15CustomerCreditService\x12j\n" +
	"\x11GetCustomerCredit\x12).customer.credit.GetCustomerCreditRequest\x1a*.customer.credit.GetCustomerCreditResponse\x12[\n" +
	"\fChargeCredit\x12$.customer.credit.ChargeCreditRequest\x1a%.customer.credit.ChargeCreditResponse\x12^\n" +
	"\rReleaseCredit\x12%.customer.credit.ReleaseCreditRequest\x1a&.customer.credit.ReleaseCreditResponseBPZNgithub.com/InBitGT/proto-definitions/customer/customer_credit;customercreditpbb\x06proto3"

var (
	file_proto_customer_customer_credit_customer_credit_proto_rawDescOnce sync.Once
	file_proto_customer_customer_credit_customer_credit_proto_rawDescData []byte
)

func file_proto_customer_customer_credit_customer_credit_proto_rawDescGZIP() []byte {
	file_proto_customer_customer_credit_customer_credit_proto_rawDescOnce.Do(func() {
		file_proto_customer_customer_credit_customer_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_customer_customer_credit_customer_credit_proto_rawDesc), len(file_proto_customer_customer_credit_customer_credit_proto_rawDesc)))
	})
	return file_proto_customer_customer_credit_customer_credit_proto_rawDescData
}

var file_proto_customer_customer_credit_customer_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_customer_customer_credit_customer_credit_proto_goTypes = []any{
	(*GetCustomerCreditRequest)(nil),  // 0: customer.credit.GetCustomerCreditRequest
	(*GetCustomerCreditResponse)(nil), // 1: customer.credit.GetCustomerCreditResponse
	(*ChargeCreditRequest)(nil),       // 2: customer.credit.ChargeCreditRequest
	(*ChargeCreditResponse)(nil),      // 3: customer.credit.ChargeCreditResponse
	(*ReleaseCreditRequest)(nil),      // 4: customer.credit.ReleaseCreditRequest
	(*ReleaseCreditResponse)(nil),     // 5: customer.credit.ReleaseCreditResponse
}
var file_proto_customer_customer_credit_customer_credit_proto_depIdxs = []int32{
	0, // 0: customer.credit.CustomerCreditService.GetCustomerCredit:input_type -> customer.credit.GetCustomerCreditRequest
	2, // 1: customer.credit.CustomerCreditService.ChargeCredit:input_type -> customer.credit.ChargeCreditRequest
	4, // 2: customer.credit.CustomerCreditService.ReleaseCredit:input_type -> customer.credit.ReleaseCreditRequest
	1, // 3: customer.credit.CustomerCreditService.GetCustomerCredit:output_type -> customer.credit.GetCustomerCreditResponse
	3, // 4: customer.credit.CustomerCreditService.ChargeCredit:output_type -> customer.credit.ChargeCreditResponse
	5, // 5: customer.credit.CustomerCreditService.ReleaseCredit:output_type -> customer.credit.ReleaseCreditResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_customer_customer_credit_customer_credit_proto_init() }
func file_proto_customer_customer_credit_customer_credit_proto_init() {
	if File_proto_customer_customer_credit_customer_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_customer_customer_credit_customer_credit_proto_rawDesc), len(file_proto_customer_customer_credit_customer_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_customer_customer_credit_customer_credit_proto_goTypes,
		DependencyIndexes: file_proto_customer_customer_credit_customer_credit_proto_depIdxs,
		MessageInfos:      file_proto_customer_customer_credit_customer_credit_proto_msgTypes,
	}.Build()
	File_proto_customer_customer_credit_customer_credit_proto = out.File
	file_proto_customer_customer_credit_customer_credit_proto_goTypes = nil
	file_proto_customer_customer_credit_customer_credit_proto_depIdxs = nil
}
