// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/user/branch/branch.proto

package branchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BranchService_GetBranchByID_FullMethodName         = "/user.branch.BranchService/GetBranchByID"
	BranchService_GetBranchesByIDs_FullMethodName      = "/user.branch.BranchService/GetBranchesByIDs"
	BranchService_GetBranchesByTenantID_FullMethodName = "/user.branch.BranchService/GetBranchesByTenantID"
)

// BranchServiceClient is the client API for BranchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BranchServiceClient interface {
	GetBranchByID(ctx context.Context, in *GetBranchByIDRequest, opts ...grpc.CallOption) (*GetBranchByIDResponse, error)
	GetBranchesByIDs(ctx context.Context, in *GetBranchesByIDsRequest, opts ...grpc.CallOption) (*GetBranchesByIDsResponse, error)
	GetBranchesByTenantID(ctx context.Context, in *GetBranchesByTenantIDRequest, opts ...grpc.CallOption) (*GetBranchesByIDsResponse, error)
}

type branchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBranchServiceClient(cc grpc.ClientConnInterface) BranchServiceClient {
	return &branchServiceClient{cc}
}

func (c *branchServiceClient) GetBranchByID(ctx context.Context, in *GetBranchByIDRequest, opts ...grpc.CallOption) (*GetBranchByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchByIDResponse)
	err := c.cc.Invoke(ctx, BranchService_GetBranchByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchServiceClient) GetBranchesByIDs(ctx context.Context, in *GetBranchesByIDsRequest, opts ...grpc.CallOption) (*GetBranchesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchesByIDsResponse)
	err := c.cc.Invoke(ctx, BranchService_GetBranchesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchServiceClient) GetBranchesByTenantID(ctx context.Context, in *GetBranchesByTenantIDRequest, opts ...grpc.CallOption) (*GetBranchesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchesByIDsResponse)
	err := c.cc.Invoke(ctx, BranchService_GetBranchesByTenantID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranchServiceServer is the server API for BranchService service.
// All implementations must embed UnimplementedBranchServiceServer
// for forward compatibility.
type BranchServiceServer interface {
	GetBranchByID(context.Context, *GetBranchByIDRequest) (*GetBranchByIDResponse, error)
	GetBranchesByIDs(context.Context, *GetBranchesByIDsRequest) (*GetBranchesByIDsResponse, error)
	GetBranchesByTenantID(context.Context, *GetBranchesByTenantIDRequest) (*GetBranchesByIDsResponse, error)
	mustEmbedUnimplementedBranchServiceServer()
}

// UnimplementedBranchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBranchServiceServer struct{}

func (UnimplementedBranchServiceServer) GetBranchByID(context.Context, *GetBranchByIDRequest) (*GetBranchByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranchByID not implemented")
}
func (UnimplementedBranchServiceServer) GetBranchesByIDs(context.Context, *GetBranchesByIDsRequest) (*GetBranchesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranchesByIDs not implemented")
}
func (UnimplementedBranchServiceServer) GetBranchesByTenantID(context.Context, *GetBranchesByTenantIDRequest) (*GetBranchesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranchesByTenantID not implemented")
}
func (UnimplementedBranchServiceServer) mustEmbedUnimplementedBranchServiceServer() {}
func (UnimplementedBranchServiceServer) testEmbeddedByValue()                       {}

// UnsafeBranchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BranchServiceServer will
// result in compilation errors.
type UnsafeBranchServiceServer interface {
	mustEmbedUnimplementedBranchServiceServer()
}

func RegisterBranchServiceServer(s grpc.ServiceRegistrar, srv BranchServiceServer) {
	// If the following call panics, it indicates UnimplementedBranchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BranchService_ServiceDesc, srv)
}

func _BranchService_GetBranchByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchServiceServer).GetBranchByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchService_GetBranchByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchServiceServer).GetBranchByID(ctx, req.(*GetBranchByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchService_GetBranchesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchServiceServer).GetBranchesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchService_GetBranchesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchServiceServer).GetBranchesByIDs(ctx, req.(*GetBranchesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchService_GetBranchesByTenantID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesByTenantIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchServiceServer).GetBranchesByTenantID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchService_GetBranchesByTenantID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchServiceServer).GetBranchesByTenantID(ctx, req.(*GetBranchesByTenantIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BranchService_ServiceDesc is the grpc.ServiceDesc for BranchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BranchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.branch.BranchService",
	HandlerType: (*BranchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBranchByID",
			Handler:    _BranchService_GetBranchByID_Handler,
		},
		{
			MethodName: "GetBranchesByIDs",
			Handler:    _BranchService_GetBranchesByIDs_Handler,
		},
		{
			MethodName: "GetBranchesByTenantID",
			Handler:    _BranchService_GetBranchesByTenantID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/branch/branch.proto",
}
