// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user/branch/branch.proto

package branchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressData) Reset() {
	*x = AddressData{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressData) ProtoMessage() {}

func (x *AddressData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressData.ProtoReflect.Descriptor instead.
func (*AddressData) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{0}
}

func (x *AddressData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressData) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *AddressData) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *AddressData) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AddressData) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AddressData) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type BranchData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddressId     uint64                 `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Address       *AddressData           `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TenantId      uint64                 `protobuf:"varint,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchData) Reset() {
	*x = BranchData{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchData) ProtoMessage() {}

func (x *BranchData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchData.ProtoReflect.Descriptor instead.
func (*BranchData) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{1}
}

func (x *BranchData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BranchData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BranchData) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *BranchData) GetAddress() *AddressData {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BranchData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BranchData) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetBranchByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchByIDRequest) Reset() {
	*x = GetBranchByIDRequest{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchByIDRequest) ProtoMessage() {}

func (x *GetBranchByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBranchByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{2}
}

func (x *GetBranchByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBranchByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Branch        *BranchData            `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchByIDResponse) Reset() {
	*x = GetBranchByIDResponse{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchByIDResponse) ProtoMessage() {}

func (x *GetBranchByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchByIDResponse.ProtoReflect.Descriptor instead.
func (*GetBranchByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{3}
}

func (x *GetBranchByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBranchByIDResponse) GetBranch() *BranchData {
	if x != nil {
		return x.Branch
	}
	return nil
}

type GetBranchesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchesByIDsRequest) Reset() {
	*x = GetBranchesByIDsRequest{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchesByIDsRequest) ProtoMessage() {}

func (x *GetBranchesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetBranchesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{4}
}

func (x *GetBranchesByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetBranchesByTenantIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchesByTenantIDRequest) Reset() {
	*x = GetBranchesByTenantIDRequest{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchesByTenantIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchesByTenantIDRequest) ProtoMessage() {}

func (x *GetBranchesByTenantIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchesByTenantIDRequest.ProtoReflect.Descriptor instead.
func (*GetBranchesByTenantIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{5}
}

func (x *GetBranchesByTenantIDRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetBranchesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Branches      []*BranchData          `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchesByIDsResponse) Reset() {
	*x = GetBranchesByIDsResponse{}
	mi := &file_proto_user_branch_branch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchesByIDsResponse) ProtoMessage() {}

func (x *GetBranchesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_branch_branch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetBranchesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_branch_branch_proto_rawDescGZIP(), []int{6}
}

func (x *GetBranchesByIDsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBranchesByIDsResponse) GetBranches() []*BranchData {
	if x != nil {
		return x.Branches
	}
	return nil
}

var File_proto_user_branch_branch_proto protoreflect.FileDescriptor

const file_proto_user_branch_branch_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/user/branch/branch.proto\x12\vuser.branch\"\xae\x01\n" +
	"\vAddressData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\"\xc2\x01\n" +
	"\n" +
	"BranchData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\x04R\taddressId\x122\n" +
	"\aaddress\x18\x04 \x01(\v2\x18.user.branch.AddressDataR\aaddress\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\x04R\btenantId\"&\n" +
	"\x14GetBranchByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"b\n" +
	"\x15GetBranchByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06branch\x18\x02 \x01(\v2\x17.user.branch.BranchDataR\x06branch\"+\n" +
	"\x17GetBranchesByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\";\n" +
	"\x1cGetBranchesByTenantIDRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\"i\n" +
	"\x18GetBranchesByIDsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\bbranches\x18\x02 \x03(\v2\x17.user.branch.BranchDataR\bbranches2\xb3\x02\n" +
	"\rBranchService\x12V\n" +
	"\rGetBranchByID\x12!.user.branch.GetBranchByIDRequest\x1a\".user.branch.GetBranchByIDResponse\x12_\n" +
	"\x10GetBranchesByIDs\x12$.user.branch.GetBranchesByIDsRequest\x1a%.user.branch.GetBranchesByIDsResponse\x12i\n" +
	"\x15GetBranchesByTenantID\x12).user.branch.GetBranchesByTenantIDRequest\x1a%.user.branch.GetBranchesByIDsResponseB;Z9github.com/InBitGT/proto-definitions/user/branch;branchpbb\x06proto3"

var (
	file_proto_user_branch_branch_proto_rawDescOnce sync.Once
	file_proto_user_branch_branch_proto_rawDescData []byte
)

func file_proto_user_branch_branch_proto_rawDescGZIP() []byte {
	file_proto_user_branch_branch_proto_rawDescOnce.Do(func() {
		file_proto_user_branch_branch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_branch_branch_proto_rawDesc), len(file_proto_user_branch_branch_proto_rawDesc)))
	})
	return file_proto_user_branch_branch_proto_rawDescData
}

var file_proto_user_branch_branch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_user_branch_branch_proto_goTypes = []any{
	(*AddressData)(nil),                  // 0: user.branch.AddressData
	(*BranchData)(nil),                   // 1: user.branch.BranchData
	(*GetBranchByIDRequest)(nil),         // 2: user.branch.GetBranchByIDRequest
	(*GetBranchByIDResponse)(nil),        // 3: user.branch.GetBranchByIDResponse
	(*GetBranchesByIDsRequest)(nil),      // 4: user.branch.GetBranchesByIDsRequest
	(*GetBranchesByTenantIDRequest)(nil), // 5: user.branch.GetBranchesByTenantIDRequest
	(*GetBranchesByIDsResponse)(nil),     // 6: user.branch.GetBranchesByIDsResponse
}
var file_proto_user_branch_branch_proto_depIdxs = []int32{
	0, // 0: user.branch.BranchData.address:type_name -> user.branch.AddressData
	1, // 1: user.branch.GetBranchByIDResponse.branch:type_name -> user.branch.BranchData
	1, // 2: user.branch.GetBranchesByIDsResponse.branches:type_name -> user.branch.BranchData
	2, // 3: user.branch.BranchService.GetBranchByID:input_type -> user.branch.GetBranchByIDRequest
	4, // 4: user.branch.BranchService.GetBranchesByIDs:input_type -> user.branch.GetBranchesByIDsRequest
	5, // 5: user.branch.BranchService.GetBranchesByTenantID:input_type -> user.branch.GetBranchesByTenantIDRequest
	3, // 6: user.branch.BranchService.GetBranchByID:output_type -> user.branch.GetBranchByIDResponse
	6, // 7: user.branch.BranchService.GetBranchesByIDs:output_type -> user.branch.GetBranchesByIDsResponse
	6, // 8: user.branch.BranchService.GetBranchesByTenantID:output_type -> user.branch.GetBranchesByIDsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_branch_branch_proto_init() }
func file_proto_user_branch_branch_proto_init() {
	if File_proto_user_branch_branch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_branch_branch_proto_rawDesc), len(file_proto_user_branch_branch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_branch_branch_proto_goTypes,
		DependencyIndexes: file_proto_user_branch_branch_proto_depIdxs,
		MessageInfos:      file_proto_user_branch_branch_proto_msgTypes,
	}.Build()
	File_proto_user_branch_branch_proto = out.File
	file_proto_user_branch_branch_proto_goTypes = nil
	file_proto_user_branch_branch_proto_depIdxs = nil
}
